<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>3 Resistance Models | Landscape Genetic Data Analysis</title>
  <meta name="description" content="A textbook for the use of R in spatial genetic data analysis.">
  <meta name="generator" content="bookdown  and GitBook 2.6.7">

  <meta property="og:title" content="3 Resistance Models | Landscape Genetic Data Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A textbook for the use of R in spatial genetic data analysis." />
  <meta name="github-repo" content="dyerlab/AMG" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="3 Resistance Models | Landscape Genetic Data Analysis" />
  
  <meta name="twitter:description" content="A textbook for the use of R in spatial genetic data analysis." />
  

<meta name="author" content="Rodney J. Dyer">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="genetic-data.html">
<link rel="next" href="space-networks.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />







<script src="libs/htmlwidgets-1.3/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.5/datatables.js"></script>
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.10.16/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.10.16/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.0.0/css/crosstalk.css" rel="stylesheet" />
<script src="libs/crosstalk-1.0.0/js/crosstalk.min.js"></script>
<script src="libs/d3-4.5.0/d3.min.js"></script>
<script src="libs/dendroNetwork-binding-0.4/dendroNetwork.js"></script>
<script src="libs/forceNetwork-binding-0.4/forceNetwork.js"></script>


<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="media/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Frontmatter</a></li>
<li class="chapter" data-level="1" data-path="spatial-data.html"><a href="spatial-data.html"><i class="fa fa-check"></i><b>1</b> Spatial Data</a><ul>
<li class="chapter" data-level="1.1" data-path="spatial-data.html"><a href="spatial-data.html#synopsis"><i class="fa fa-check"></i><b>1.1</b> Synopsis</a></li>
<li class="chapter" data-level="1.2" data-path="spatial-data.html"><a href="spatial-data.html#objectives"><i class="fa fa-check"></i><b>1.2</b> Objectives</a></li>
<li class="chapter" data-level="1.3" data-path="spatial-data.html"><a href="spatial-data.html#logistics-on-data"><i class="fa fa-check"></i><b>1.3</b> Logistics on Data</a></li>
<li class="chapter" data-level="1.4" data-path="spatial-data.html"><a href="spatial-data.html#projections"><i class="fa fa-check"></i><b>1.4</b> Projections</a><ul>
<li class="chapter" data-level="1.4.1" data-path="spatial-data.html"><a href="spatial-data.html#equatorial-projections"><i class="fa fa-check"></i><b>1.4.1</b> Equatorial Projections</a></li>
<li class="chapter" data-level="1.4.2" data-path="spatial-data.html"><a href="spatial-data.html#azimuth-projections"><i class="fa fa-check"></i><b>1.4.2</b> Azimuth Projections</a></li>
<li class="chapter" data-level="1.4.3" data-path="spatial-data.html"><a href="spatial-data.html#polar-conic-projections"><i class="fa fa-check"></i><b>1.4.3</b> Polar Conic Projections</a></li>
<li class="chapter" data-level="1.4.4" data-path="spatial-data.html"><a href="spatial-data.html#miscellaneous-projections"><i class="fa fa-check"></i><b>1.4.4</b> Miscellaneous Projections</a></li>
<li class="chapter" data-level="1.4.5" data-path="spatial-data.html"><a href="spatial-data.html#coordinate-systems"><i class="fa fa-check"></i><b>1.4.5</b> Coordinate Systems</a></li>
<li class="chapter" data-level="1.4.6" data-path="spatial-data.html"><a href="spatial-data.html#projection-summary"><i class="fa fa-check"></i><b>1.4.6</b> Projection Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.5" data-path="spatial-data.html"><a href="spatial-data.html#the-sp-library"><i class="fa fa-check"></i><b>1.5</b> The <code>sp</code> Library</a><ul>
<li class="chapter" data-level="1.5.1" data-path="spatial-data.html"><a href="spatial-data.html#points"><i class="fa fa-check"></i><b>1.5.1</b> Points</a></li>
<li class="chapter" data-level="1.5.2" data-path="spatial-data.html"><a href="spatial-data.html#lines"><i class="fa fa-check"></i><b>1.5.2</b> Lines</a></li>
<li class="chapter" data-level="1.5.3" data-path="spatial-data.html"><a href="spatial-data.html#polygons"><i class="fa fa-check"></i><b>1.5.3</b> Polygons</a></li>
<li class="chapter" data-level="1.5.4" data-path="spatial-data.html"><a href="spatial-data.html#projecting-sp-objects."><i class="fa fa-check"></i><b>1.5.4</b> Projecting <code>sp</code> objects.</a></li>
<li class="chapter" data-level="1.5.5" data-path="spatial-data.html"><a href="spatial-data.html#points-lines-and-polygons-in-ggplot"><i class="fa fa-check"></i><b>1.5.5</b> Points, Lines, and Polygons in ggplot</a></li>
</ul></li>
<li class="chapter" data-level="1.6" data-path="spatial-data.html"><a href="spatial-data.html#rasters"><i class="fa fa-check"></i><b>1.6</b> Rasters</a></li>
<li class="chapter" data-level="1.7" data-path="spatial-data.html"><a href="spatial-data.html#modifying-rasters"><i class="fa fa-check"></i><b>1.7</b> Modifying Rasters</a><ul>
<li class="chapter" data-level="1.7.1" data-path="spatial-data.html"><a href="spatial-data.html#stacks-of-rasters"><i class="fa fa-check"></i><b>1.7.1</b> Stacks of Rasters</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="spatial-data.html"><a href="spatial-data.html#rasters-ggplot"><i class="fa fa-check"></i><b>1.8</b> Rasters &amp; ggplot</a></li>
<li class="chapter" data-level="1.9" data-path="spatial-data.html"><a href="spatial-data.html#d-visualization"><i class="fa fa-check"></i><b>1.9</b> 3D Visualization</a></li>
<li class="chapter" data-level="1.10" data-path="spatial-data.html"><a href="spatial-data.html#saving-exporting-vector-raster-objects"><i class="fa fa-check"></i><b>1.10</b> Saving &amp; Exporting Vector &amp; Raster Objects</a></li>
<li class="chapter" data-level="1.11" data-path="spatial-data.html"><a href="spatial-data.html#raster-manipulation"><i class="fa fa-check"></i><b>1.11</b> Raster Manipulation</a><ul>
<li class="chapter" data-level="1.11.1" data-path="spatial-data.html"><a href="spatial-data.html#cropping-rasters"><i class="fa fa-check"></i><b>1.11.1</b> Cropping Rasters</a></li>
<li class="chapter" data-level="1.11.2" data-path="spatial-data.html"><a href="spatial-data.html#cropping-rasters-via-polygons"><i class="fa fa-check"></i><b>1.11.2</b> Cropping Rasters Via Polygons</a></li>
<li class="chapter" data-level="1.11.3" data-path="spatial-data.html"><a href="spatial-data.html#cropping-rasters-via-convex-hull"><i class="fa fa-check"></i><b>1.11.3</b> Cropping Rasters Via Convex Hull</a></li>
<li class="chapter" data-level="1.11.4" data-path="spatial-data.html"><a href="spatial-data.html#extracting-point-data-from-rasters"><i class="fa fa-check"></i><b>1.11.4</b> Extracting Point Data From Rasters</a></li>
<li class="chapter" data-level="1.11.5" data-path="spatial-data.html"><a href="spatial-data.html#extracting-neighborhood-data-from-rasters"><i class="fa fa-check"></i><b>1.11.5</b> Extracting Neighborhood Data from Rasters</a></li>
<li class="chapter" data-level="1.11.6" data-path="spatial-data.html"><a href="spatial-data.html#reprojecting-rasters"><i class="fa fa-check"></i><b>1.11.6</b> Reprojecting Rasters</a></li>
</ul></li>
<li class="chapter" data-level="1.12" data-path="spatial-data.html"><a href="spatial-data.html#questions"><i class="fa fa-check"></i><b>1.12</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="genetic-data.html"><a href="genetic-data.html"><i class="fa fa-check"></i><b>2</b> Genetic Data</a><ul>
<li class="chapter" data-level="2.1" data-path="genetic-data.html"><a href="genetic-data.html#synopsis-1"><i class="fa fa-check"></i><b>2.1</b> Synopsis</a></li>
<li class="chapter" data-level="2.2" data-path="genetic-data.html"><a href="genetic-data.html#objectives-1"><i class="fa fa-check"></i><b>2.2</b> Objectives</a></li>
<li class="chapter" data-level="2.3" data-path="genetic-data.html"><a href="genetic-data.html#genetic-markers-types-and-usage"><i class="fa fa-check"></i><b>2.3</b> Genetic Markers, Types and Usage</a><ul>
<li class="chapter" data-level="2.3.1" data-path="genetic-data.html"><a href="genetic-data.html#loading-external-data"><i class="fa fa-check"></i><b>2.3.1</b> Loading External Data</a></li>
<li class="chapter" data-level="2.3.2" data-path="genetic-data.html"><a href="genetic-data.html#built-in-data-sets"><i class="fa fa-check"></i><b>2.3.2</b> Built-In Data Sets</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="genetic-data.html"><a href="genetic-data.html#allele-frequencies"><i class="fa fa-check"></i><b>2.4</b> Allele Frequencies</a></li>
<li class="chapter" data-level="2.5" data-path="genetic-data.html"><a href="genetic-data.html#hardy-weinberg-equilibrium"><i class="fa fa-check"></i><b>2.5</b> Hardy-Weinberg Equilibrium</a><ul>
<li class="chapter" data-level="2.5.1" data-path="genetic-data.html"><a href="genetic-data.html#genetic-assumptions"><i class="fa fa-check"></i><b>2.5.1</b> Genetic Assumptions</a></li>
<li class="chapter" data-level="2.5.2" data-path="genetic-data.html"><a href="genetic-data.html#punnet-squares"><i class="fa fa-check"></i><b>2.5.2</b> Punnet Squares</a></li>
<li class="chapter" data-level="2.5.3" data-path="genetic-data.html"><a href="genetic-data.html#evolutionary-assumptions"><i class="fa fa-check"></i><b>2.5.3</b> Evolutionary Assumptions</a></li>
<li class="chapter" data-level="2.5.4" data-path="genetic-data.html"><a href="genetic-data.html#the-mechanics"><i class="fa fa-check"></i><b>2.5.4</b> The Mechanics</a></li>
<li class="chapter" data-level="2.5.5" data-path="genetic-data.html"><a href="genetic-data.html#trans-generational-transition-probabilities"><i class="fa fa-check"></i><b>2.5.5</b> Trans-Generational Transition Probabilities</a></li>
<li class="chapter" data-level="2.5.6" data-path="genetic-data.html"><a href="genetic-data.html#consequences-of-hwe"><i class="fa fa-check"></i><b>2.5.6</b> Consequences of HWE</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="genetic-data.html"><a href="genetic-data.html#genetic-diversity"><i class="fa fa-check"></i><b>2.6</b> Genetic Diversity</a><ul>
<li class="chapter" data-level="2.6.1" data-path="genetic-data.html"><a href="genetic-data.html#allelic-diversity"><i class="fa fa-check"></i><b>2.6.1</b> Allelic Diversity</a></li>
<li class="chapter" data-level="2.6.2" data-path="genetic-data.html"><a href="genetic-data.html#genotypic-diversity"><i class="fa fa-check"></i><b>2.6.2</b> Genotypic Diversity</a></li>
<li class="chapter" data-level="2.6.3" data-path="genetic-data.html"><a href="genetic-data.html#samples-from-several-locales"><i class="fa fa-check"></i><b>2.6.3</b> Samples from Several Locales</a></li>
<li class="chapter" data-level="2.6.4" data-path="genetic-data.html"><a href="genetic-data.html#multilocus-diversity"><i class="fa fa-check"></i><b>2.6.4</b> Multilocus Diversity</a></li>
<li class="chapter" data-level="2.6.5" data-path="genetic-data.html"><a href="genetic-data.html#inbreeding"><i class="fa fa-check"></i><b>2.6.5</b> Inbreeding</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="genetic-data.html"><a href="genetic-data.html#rarefaction"><i class="fa fa-check"></i><b>2.7</b> Rarefaction</a><ul>
<li class="chapter" data-level="2.7.1" data-path="genetic-data.html"><a href="genetic-data.html#mapping-diversity"><i class="fa fa-check"></i><b>2.7.1</b> Mapping Diversity</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="genetic-data.html"><a href="genetic-data.html#genetic-distance"><i class="fa fa-check"></i><b>2.8</b> Genetic Distance</a><ul>
<li class="chapter" data-level="2.8.1" data-path="genetic-data.html"><a href="genetic-data.html#individual-genetic-distance"><i class="fa fa-check"></i><b>2.8.1</b> Individual Genetic Distance</a></li>
<li class="chapter" data-level="2.8.2" data-path="genetic-data.html"><a href="genetic-data.html#population-level-genetic-distances"><i class="fa fa-check"></i><b>2.8.2</b> Population-Level Genetic Distances</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="genetic-data.html"><a href="genetic-data.html#genetic-structure"><i class="fa fa-check"></i><b>2.9</b> Genetic Structure</a></li>
<li class="chapter" data-level="2.10" data-path="genetic-data.html"><a href="genetic-data.html#f-statistics-and-thier-ilk"><i class="fa fa-check"></i><b>2.10</b> F-Statistics and Thier Ilk</a><ul>
<li class="chapter" data-level="2.10.1" data-path="genetic-data.html"><a href="genetic-data.html#issues-with-fixation-indices"><i class="fa fa-check"></i><b>2.10.1</b> Issues with Fixation Indices</a></li>
<li class="chapter" data-level="2.10.2" data-path="genetic-data.html"><a href="genetic-data.html#additional-x_st-like-parameters"><i class="fa fa-check"></i><b>2.10.2</b> Additional <span class="math inline">\(X_{ST}\)</span>-like Parameters</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="genetic-data.html"><a href="genetic-data.html#statistical-structure"><i class="fa fa-check"></i><b>2.11</b> Statistical Structure</a><ul>
<li class="chapter" data-level="2.11.1" data-path="genetic-data.html"><a href="genetic-data.html#final-thoughts-on-structure"><i class="fa fa-check"></i><b>2.11.1</b> Final Thoughts on Structure</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="genetic-data.html"><a href="genetic-data.html#questions-1"><i class="fa fa-check"></i><b>2.12</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="resistance-models.html"><a href="resistance-models.html"><i class="fa fa-check"></i><b>3</b> Resistance Models</a><ul>
<li class="chapter" data-level="3.1" data-path="resistance-models.html"><a href="resistance-models.html#synopsis-2"><i class="fa fa-check"></i><b>3.1</b> Synopsis</a></li>
<li class="chapter" data-level="3.2" data-path="resistance-models.html"><a href="resistance-models.html#objectives-2"><i class="fa fa-check"></i><b>3.2</b> Objectives</a></li>
<li class="chapter" data-level="3.3" data-path="resistance-models.html"><a href="resistance-models.html#resistance-costs"><i class="fa fa-check"></i><b>3.3</b> Resistance Costs</a><ul>
<li class="chapter" data-level="3.3.1" data-path="resistance-models.html"><a href="resistance-models.html#working-with-remotely-sensed-data"><i class="fa fa-check"></i><b>3.3.1</b> Working with Remotely Sensed Data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="resistance-models.html"><a href="resistance-models.html#estimating-distances-on-resistance-rasters"><i class="fa fa-check"></i><b>3.4</b> Estimating Distances on Resistance Rasters</a><ul>
<li class="chapter" data-level="3.4.1" data-path="resistance-models.html"><a href="resistance-models.html#least-cost-distance"><i class="fa fa-check"></i><b>3.4.1</b> Least Cost Distance</a></li>
<li class="chapter" data-level="3.4.2" data-path="resistance-models.html"><a href="resistance-models.html#all-paths-circuitscape-distances"><i class="fa fa-check"></i><b>3.4.2</b> All Paths (CircuitScape) Distances</a></li>
<li class="chapter" data-level="3.4.3" data-path="resistance-models.html"><a href="resistance-models.html#logistical-issues"><i class="fa fa-check"></i><b>3.4.3</b> Logistical Issues</a></li>
<li class="chapter" data-level="3.4.4" data-path="resistance-models.html"><a href="resistance-models.html#pixel-size-and-path-lengths"><i class="fa fa-check"></i><b>3.4.4</b> Pixel Size and Path Lengths</a></li>
<li class="chapter" data-level="3.4.5" data-path="resistance-models.html"><a href="resistance-models.html#scaling-resistance"><i class="fa fa-check"></i><b>3.4.5</b> Scaling Resistance</a></li>
<li class="chapter" data-level="3.4.6" data-path="resistance-models.html"><a href="resistance-models.html#final-thoughts-on-raster-manipulations"><i class="fa fa-check"></i><b>3.4.6</b> Final Thoughts on Raster Manipulations</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="resistance-models.html"><a href="resistance-models.html#resistance-models-1"><i class="fa fa-check"></i><b>3.5</b> Resistance Models</a><ul>
<li class="chapter" data-level="3.5.1" data-path="resistance-models.html"><a href="resistance-models.html#the-mantel-test"><i class="fa fa-check"></i><b>3.5.1</b> The Mantel Test</a></li>
<li class="chapter" data-level="3.5.2" data-path="resistance-models.html"><a href="resistance-models.html#the-partial-mantel"><i class="fa fa-check"></i><b>3.5.2</b> The Partial Mantel</a></li>
<li class="chapter" data-level="3.5.3" data-path="resistance-models.html"><a href="resistance-models.html#distance-regression"><i class="fa fa-check"></i><b>3.5.3</b> Distance Regression</a></li>
<li class="chapter" data-level="3.5.4" data-path="resistance-models.html"><a href="resistance-models.html#model-comparisons-concerns"><i class="fa fa-check"></i><b>3.5.4</b> Model Comparisons &amp; Concerns</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="resistance-models.html"><a href="resistance-models.html#questions-2"><i class="fa fa-check"></i><b>3.6</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="space-networks.html"><a href="space-networks.html"><i class="fa fa-check"></i><b>4</b> Space &amp; Networks</a><ul>
<li class="chapter" data-level="4.1" data-path="space-networks.html"><a href="space-networks.html#synopsis-3"><i class="fa fa-check"></i><b>4.1</b> Synopsis</a></li>
<li class="chapter" data-level="4.2" data-path="space-networks.html"><a href="space-networks.html#objectives-3"><i class="fa fa-check"></i><b>4.2</b> Objectives</a></li>
<li class="chapter" data-level="4.3" data-path="space-networks.html"><a href="space-networks.html#admixture"><i class="fa fa-check"></i><b>4.3</b> Admixture</a></li>
<li class="chapter" data-level="4.4" data-path="space-networks.html"><a href="space-networks.html#ordination"><i class="fa fa-check"></i><b>4.4</b> Ordination</a><ul>
<li class="chapter" data-level="4.4.1" data-path="space-networks.html"><a href="space-networks.html#principal-component-rotations"><i class="fa fa-check"></i><b>4.4.1</b> Principal Component Rotations</a></li>
<li class="chapter" data-level="4.4.2" data-path="space-networks.html"><a href="space-networks.html#hierarchical-clustering"><i class="fa fa-check"></i><b>4.4.2</b> Hierarchical Clustering</a></li>
<li class="chapter" data-level="4.4.3" data-path="space-networks.html"><a href="space-networks.html#interactive-tree-display"><i class="fa fa-check"></i><b>4.4.3</b> Interactive Tree Display</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="space-networks.html"><a href="space-networks.html#networks"><i class="fa fa-check"></i><b>4.5</b> Networks</a><ul>
<li class="chapter" data-level="4.5.1" data-path="space-networks.html"><a href="space-networks.html#node-edge-attributes"><i class="fa fa-check"></i><b>4.5.1</b> Node &amp; Edge Attributes</a></li>
<li class="chapter" data-level="4.5.2" data-path="space-networks.html"><a href="space-networks.html#plotting-a-graphs"><i class="fa fa-check"></i><b>4.5.2</b> Plotting a Graphs</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="space-networks.html"><a href="space-networks.html#mapping-networks"><i class="fa fa-check"></i><b>4.6</b> Mapping Networks</a></li>
<li class="chapter" data-level="4.7" data-path="space-networks.html"><a href="space-networks.html#genetic-distance-graphs"><i class="fa fa-check"></i><b>4.7</b> Genetic Distance Graphs</a></li>
<li class="chapter" data-level="4.8" data-path="space-networks.html"><a href="space-networks.html#population-graphs"><i class="fa fa-check"></i><b>4.8</b> Population Graphs</a></li>
<li class="chapter" data-level="4.9" data-path="space-networks.html"><a href="space-networks.html#adding-data-to-a-graph"><i class="fa fa-check"></i><b>4.9</b> Adding data to a graph</a><ul>
<li class="chapter" data-level="4.9.1" data-path="space-networks.html"><a href="space-networks.html#plotting-a-graph-using-ggplot2-routines"><i class="fa fa-check"></i><b>4.9.1</b> Plotting a graph using <strong>ggplot2</strong> routines</a></li>
<li class="chapter" data-level="4.9.2" data-path="space-networks.html"><a href="space-networks.html#reading-existing-popgraph-files"><i class="fa fa-check"></i><b>4.9.2</b> Reading Existing <strong>popgraph</strong> Files</a></li>
<li class="chapter" data-level="4.9.3" data-path="space-networks.html"><a href="space-networks.html#saving-population-graph-objects"><i class="fa fa-check"></i><b>4.9.3</b> Saving Population Graph Objects</a></li>
<li class="chapter" data-level="4.9.4" data-path="space-networks.html"><a href="space-networks.html#interactive-networks"><i class="fa fa-check"></i><b>4.9.4</b> Interactive Networks</a></li>
<li class="chapter" data-level="4.9.5" data-path="space-networks.html"><a href="space-networks.html#spatial-population-graphs"><i class="fa fa-check"></i><b>4.9.5</b> Spatial Population Graphs</a></li>
<li class="chapter" data-level="4.9.6" data-path="space-networks.html"><a href="space-networks.html#integrating-google-and-ggplot2-for-plotting"><i class="fa fa-check"></i><b>4.9.6</b> Integrating Google and <strong>ggplot2</strong> for Plotting</a></li>
<li class="chapter" data-level="4.9.7" data-path="space-networks.html"><a href="space-networks.html#integrating-raster-maps"><i class="fa fa-check"></i><b>4.9.7</b> Integrating Raster Maps</a></li>
<li class="chapter" data-level="4.9.8" data-path="space-networks.html"><a href="space-networks.html#extracting-spatial-data-using-population-graphs"><i class="fa fa-check"></i><b>4.9.8</b> Extracting Spatial Data Using Population Graphs</a></li>
</ul></li>
<li class="chapter" data-level="4.10" data-path="space-networks.html"><a href="space-networks.html#extracting-graph-theoretic-parameters"><i class="fa fa-check"></i><b>4.10</b> Extracting Graph-Theoretic Parameters</a><ul>
<li class="chapter" data-level="4.10.1" data-path="space-networks.html"><a href="space-networks.html#matrix-representations-of-population-graph-objects"><i class="fa fa-check"></i><b>4.10.1</b> Matrix Representations of Population Graph Objects</a></li>
<li class="chapter" data-level="4.10.2" data-path="space-networks.html"><a href="space-networks.html#edge-specific-parameters"><i class="fa fa-check"></i><b>4.10.2</b> Edge Specific Parameters</a></li>
</ul></li>
<li class="chapter" data-level="4.11" data-path="space-networks.html"><a href="space-networks.html#testing-for-topological-congruence"><i class="fa fa-check"></i><b>4.11</b> Testing for Topological Congruence</a></li>
<li class="chapter" data-level="4.12" data-path="space-networks.html"><a href="space-networks.html#questions-3"><i class="fa fa-check"></i><b>4.12</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="quantitative-genetics.html"><a href="quantitative-genetics.html"><i class="fa fa-check"></i><b>5</b> Quantitative Genetics</a><ul>
<li class="chapter" data-level="5.1" data-path="quantitative-genetics.html"><a href="quantitative-genetics.html#phenotypic-variance"><i class="fa fa-check"></i><b>5.1</b> Phenotypic Variance</a></li>
<li class="chapter" data-level="5.2" data-path="quantitative-genetics.html"><a href="quantitative-genetics.html#data-examples"><i class="fa fa-check"></i><b>5.2</b> Data Examples</a><ul>
<li class="chapter" data-level="5.2.1" data-path="quantitative-genetics.html"><a href="quantitative-genetics.html#measured-traits"><i class="fa fa-check"></i><b>5.2.1</b> Measured Traits</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="quantitative-genetics.html"><a href="quantitative-genetics.html#heritability"><i class="fa fa-check"></i><b>5.3</b> Heritability</a></li>
<li class="chapter" data-level="5.4" data-path="quantitative-genetics.html"><a href="quantitative-genetics.html#questions-4"><i class="fa fa-check"></i><b>5.4</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-cited.html"><a href="references-cited.html"><i class="fa fa-check"></i>References Cited</a></li>
<li class="chapter" data-level="" data-path="rgdal-rgeos.html"><a href="rgdal-rgeos.html"><i class="fa fa-check"></i>RGDAL &amp; RGEOS</a></li>
<li class="divider"></li>
<li><a href="http://dyerlab.com" target="blank">the Dyer Laboratory</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Landscape Genetic Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="resistance-models" class="section level1">
<h1><span class="header-section-number">3</span> Resistance Models</h1>
<div class="figure">
<img src="media/ch_mountain.jpg" />

</div>
<div id="synopsis-2" class="section level2">
<h2><span class="header-section-number">3.1</span> Synopsis</h2>
<p>One of the characteristics of landscape genetics studies, maybe even a defining feature, is its use of resistance and distance approaches to understanding the spatial distribution of genetic structure and <em>hopefully</em> to use it in support of characterizing landscape mediated connectivity. In this activity, we will explore how to characterize and estimate separation and delve into a approaches for understanding how we can analyze similarly defined genetic distances.</p>
</div>
<div id="objectives-2" class="section level2">
<h2><span class="header-section-number">3.2</span> Objectives</h2>
<p>In this section, we focus on the characterization and analysis of distance matrices. By the time you finish this activity, you should be able to:</p>
<ol style="list-style-type: decimal">
<li>Create, develop, and manipulate matrices and rasters to be used in resistance modeling analyses.</li>
<li>Understand and use alternative methods for estimating separation among locations using resistance rasters</li>
<li>Examine different statistical models applicable to distance-based resistance modeling.</li>
</ol>
</div>
<div id="resistance-costs" class="section level2">
<h2><span class="header-section-number">3.3</span> Resistance Costs</h2>
<p>The data set that we are going to be using consists of several a set of <em>Cornus florida</em> trees, acting as pollen recipients. These trees are situated on ~170ha site, co-distributed with <em>Ilex</em> species in the understory and over-topped with both <em>Pinus</em> and <em>Quercus</em> canopy dominants. Seeds were collected from several maternal individuals, germinated, and genotypes. These data were collected to examine pollen-mediated gene flow. Maternal locations are considered as spatial sampling of a ‘pollen pool’, whose spatial structure is determined by the physical and spatial separation of pollen donor and recipient trees. In addition to the genetic and spatial data, the following features were also measured using remote sensing (LiDAR &amp; Hyper-spectral Imaging):</p>
<ul>
<li>General Features<br />
</li>
<li>Euclidean distance<br />
</li>
<li>Elevation similarity.<br />
</li>
<li>Forest Canopy Features<br />
</li>
<li>Coniferous vegetation (cv)<br />
</li>
<li>Mixed hardwoods (mh)<br />
</li>
<li>Open field (fd)<br />
</li>
<li>Forest Understory Features<br />
</li>
<li>Roads (rd)<br />
</li>
<li>Cornus canopies (cf)</li>
</ul>
<p>These layers are provided in the <tt>data/dogwood</tt> folder as *.asc raster files.</p>
<p>Resistance is a cost associated with movement across a landscape. In the context of landscape genetics, we assume that this parameter is what is influencing connectivity. As a raster, resistance is represented by the values stored in a raster. A feature on the landscape may either promote or retard movement. The greater the value, the more effects that may have on movement across the pixel. The example below shows conifer canopy structure across the study area. It can be that movement is hindered under the conifer canopy (left) <em>or</em> it could be restricted moving outside the conifer canopy (right).</p>
<div class="figure"><span id="fig:unnamed-chunk-158"></span>
<img src="LGDA_files/figure-html/unnamed-chunk-158-1.png" alt="Mirror resistance rasters based upon the presence of conifer canopy structure." width="672" />
<p class="caption">
Figure 3.1: Mirror resistance rasters based upon the presence of conifer canopy structure.
</p>
</div>
<p>The data we use for parameterizing resistance rasters may come from many different sources. The key here is that the proper set of features influencing connectivity and their individual interactions and resistance values are those that <em>best describe the spatial distribution of genetic variation</em>. The genotypes and where they are located are the answer, resulting from the demographic processes we are trying to analyze. Theory surrounding resistance derivations for connectivity are still being actively developed, so pay attention to the literature exciting developments are ahead.</p>
<p>We can derive resistance rasters from many sources. They may be hand digitized, wherein features of the landscape are manually mapped onto a raster. The kinds of features most easily hand digitized are those that are large in extent and continuous such as roads, barriers, rivers, and other features of course granularity.</p>
<p>Climatic data, commonly parameterized in terms of precipitation and temperature, can algorithmically derive raster cost surfaces. The accuracy of these rasters depend largely upon the region of the earth being modeled, the density of weather monitoring stations, and volatility of weather in that location. The most popular provider of climactic data is <a href="http://worldclim.org">WorldClim</a>, from which the rasters you worked with on Monday were provided.</p>
<p>Increasingly, remotely sensed data sources are being used to incorporate information into resistance rasters. Platforms collecting remotely sensed data may be satellites, fixed wing aircraft, balloons, unmanned aircraft (drones), and even hand carried devices. The rasters provided were collected by fixed wing aircraft.</p>
<div id="working-with-remotely-sensed-data" class="section level3">
<h3><span class="header-section-number">3.3.1</span> Working with Remotely Sensed Data</h3>
<p>LiDAR data generally comes in *.las or *.laz files and will have gone through some pre-processing such that each return will have an x,y, and z coordinate. Depending on the LiDAR sensor there may also be data defining the return number, intensity of the return, R,G,B data, or other classifications of ground and non-ground returns.</p>
<p>LAS files can easily have millions, or billions, of points and thus are generally very large. We will be working with data set that has been subset to a more manageable size. The original LAS files were clipped to an area of interest using LAStools which is available at <a href="https://rapidlasso.com/lastools/" class="uri">https://rapidlasso.com/lastools/</a> There is a GUI for Windows operating systems and can be run via command line on Mac.</p>
<p>Depending on the data source, certain classifications may have already been assigned to returns such as ground (=2) and non-ground (=1). If data is not classified as ground/not ground you will need to run lasground which will extract ground points from you data set. Subsequently las height will determine the height above ground of each return. Next LASclassify will allow you to extract horizontal slices from the point cloud.</p>
<p>There are two example *.las files, <tt>lowvegetation.las</tt> and <tt>mediumvegetation.las</tt> in the folder <tt>data/lidar/</tt> that you can look at later. Given the size of these files and the time it takes to translate them into rasters, we have provided pre-existing rasters with 0.5 m spatial resolution in the same folder. There are three, <tt>High05.asc</tt>, <tt>Med05.asc</tt> and <tt>Low05.asc</tt> and they can be loaded in just like any other raster. Here is the medium vegetation layer, depicting LiDAR returns in a band that is between 3.5 - 11m above the ground, presumably the space through which the pollinators will be moving. The values in the cells of this raster are the elevation of the LiDAR return and are only salient to us if we make them all the same, indicating the presence/absence of a return rather than the elevation that it was recorded as.</p>
<pre><code>## class       : RasterLayer 
## dimensions  : 2883, 1664, 4797312  (nrow, ncol, ncell)
## resolution  : 0.5, 0.5  (x, y)
## extent      : 303969.6, 304801.6, 4133236, 4134677  (xmin, xmax, ymin, ymax)
## coord. ref. : NA 
## data source : in memory
## names       : Med05 
## values      : 1, 1  (min, max)</code></pre>
<p>This is quite a detailed raster, much more detailed in scale than the <code>pines</code> one above. Given the small pixel size, you may need to zoom the raster image a bit to see the details.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">plot</span>( medVeg )</code></pre></div>
<p><img src="LGDA_files/figure-html/unnamed-chunk-160-1.png" width="672" /></p>
<p>The difference in the <code>pine</code> and <code>medVeg</code> raster resolutions brings up a salient point, and one that is perhaps not as well appreciated in the literature as it should be. The LiDAR returns are very fine grained, whereas the hyperspec data that created the <code>pine</code> raster was more course grained. However, which grain is most important for to the organism that is participating in the movement of genetic materials? It may be that for some features, organisms perceive the environment at one level of granularity and for other features they react to a different scale.</p>
<p>We would have to tune our analyses such that we can determine which pixel size is most important. Functionally, this is accomplished using the <code>aggregate</code> function, supplied with a factor (e.g., the neighborhood size to aggregate) and a function (in this case we used the <code>max</code> function).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">medVeg1 &lt;-<span class="st"> </span><span class="kw">aggregate</span>(medVeg, <span class="dt">fact=</span><span class="dv">2</span>, <span class="dt">FUN=</span>max)
medVeg2 &lt;-<span class="st"> </span><span class="kw">aggregate</span>(medVeg, <span class="dt">fact=</span><span class="dv">4</span>, <span class="dt">FUN=</span>max)
medVeg5 &lt;-<span class="st"> </span><span class="kw">aggregate</span>(medVeg, <span class="dt">fact=</span><span class="dv">10</span>, <span class="dt">FUN=</span>max)
medVeg10 &lt;-<span class="st"> </span><span class="kw">aggregate</span>(medVeg, <span class="dt">fact=</span><span class="dv">20</span>, <span class="dt">FUN=</span>max)</code></pre></div>
<p>The differences between can easily be visualized.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">mai=</span><span class="kw">c</span>(<span class="fl">0.5</span>,<span class="fl">0.5</span>,<span class="fl">0.2</span>,<span class="fl">0.2</span>))
<span class="kw">plot</span>(medVeg1, <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)
<span class="kw">plot</span>(medVeg2, <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)
<span class="kw">plot</span>(medVeg5, <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)
<span class="kw">plot</span>(medVeg10, <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)</code></pre></div>
<p><img src="LGDA_files/figure-html/unnamed-chunk-162-1.png" width="672" /></p>
<p>The salient point here is that the aggregate factor itself may be a parameter that we need to estimate during our analyses. The easiest way to do this is to build your rasters across a range of granularity and let the analyses sort out which is the most salient scale to use. We will see this approach again when we discuss the magnitude of raster costs.</p>
</div>
</div>
<div id="estimating-distances-on-resistance-rasters" class="section level2">
<h2><span class="header-section-number">3.4</span> Estimating Distances on Resistance Rasters</h2>
<p>Once we have defined one or more rasters quantifying resistance costs, we can go and estimate the distance among points on those rasters. There are several ways available for us to estimate distance. The differences in these methods are based upon the algorithm used to estimate separation and the extent of the raster used to apply these algorithms. These methods are buttressed on each end by:</p>
<ul>
<li>Least Cost Path: An optimum solution, attempting to find the shortest cost path between two points. This algorithm may produce asymmetric paths (e.g., the total cost to a location may not be the same as the distance from a location) depending on how the underlying raster is configured.</li>
<li>All Paths (CircuitScape): This algorithm attempts to capture the way in which the entire landscape influences connectivity by integrating all the potential paths between locations.</li>
</ul>
<p>These algorithms may be given the entire raster to work with or may be constrained. Some examples of constraints are items on the landscape that are impassible (e.g., a rock), either by having missing data in the raster itself or a value of resistance that makes it impossible to be considered part of a potential path. Other approaches may include the addition of corridors, within which paths may be constrained to move. These configurations are implemented by crafting additional spatial objects in the same raster space as your cost rasters.</p>
<p>As a last word of concern, you should also consider reducing the extent of your raster as much as feasible. The actual algorithm that estimates path distances (for least cost at least) is one that increases in complexity, time, and memory with the cube of the number of pixels! Similar scaling issues are involved with solving the linear equations necessary for the all paths problem. <span class="math inline">\(N^3\)</span> increases rapidly, so everything you can do to constrain its magnitude helps.</p>
<div id="least-cost-distance" class="section level3">
<h3><span class="header-section-number">3.4.1</span> Least Cost Distance</h3>
<p>A least cost path is the route between two points, say <span class="math inline">\(A \to B\)</span>, whose length is minimal. This is the <em>optimal</em> route across the landscape. Organisms or vectors of gene exchange may, or may not, move across a landscape following an <em>optimal</em> path.</p>
<div class="figure"><span id="fig:lcp-example"></span>
<img src="../media/LCP.png" alt="Estimation algorithm for least-cost path distance.  The path chosen is the one with the shortest overall distance, or at least one of the paths with equally short overall distances."  />
<p class="caption">
Figure 3.2: Estimation algorithm for least-cost path distance. The path chosen is the one with the shortest overall distance, or at least one of the paths with equally short overall distances.
</p>
</div>
<p>One way to estimate distances in R, is through the use of the <code>gdistance</code> library. In this approach, we define a transition object based upon:<br />
1. The cost distance raster. By default, the <code>transition()</code> function works on conductance, which is the inverse of resistance. In these examples, we have used a single raster, though use of <em>RasterBrick</em> objects is just as appropriate. 2. The function by which we estimate the pixel-to-pixel distances.<br />
3. The neighborhood around each pixel that we look at during each step. Options for this include:<br />
- A von Neumann neighborhood (<code>directions=4</code>) consists of the pixels immediately above, below, and on both sides of the target pixel.<br />
- A Moore’s neighborhood (<code>directions=8</code>) consisting of all pixels surrounding the target pixel (e.g., even the diagonal ones) - A Knight &amp; One-Cell Queen move (<code>directions=16</code>), which adds the next layer of cells outside of Moore’s neighborhood.</p>
<p>Once estimated, the transition object <em>must</em> be corrected for if you are either using a large extent based upon Latitude and Longitude datum (e.g., they are not unit-wise consistent in area), or you have used a <code>direction</code> option other than the von Neuman Neighborhood.</p>
<p>In the example below, I use the cost distance estimated as an absolute distance with a resistance cost of 2:1.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">require</span>(gdistance)
pine &lt;-<span class="st"> </span>pines <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
tr &lt;-<span class="st"> </span><span class="kw">transition</span>( <span class="dv">1</span><span class="op">/</span>pine, <span class="dt">transitionFunction =</span> mean, <span class="dt">directions=</span><span class="dv">4</span> )
tr &lt;-<span class="st"> </span><span class="kw">geoCorrection</span>( tr, <span class="dt">type=</span><span class="st">&quot;c&quot;</span>, <span class="dt">multpl=</span><span class="ot">FALSE</span>, <span class="dt">scl=</span><span class="ot">FALSE</span>)
tr</code></pre></div>
<pre><code>## class       : TransitionLayer 
## dimensions  : 941, 527, 495907  (nrow, ncol, ncell)
## resolution  : 1.000212, 1.000212  (x, y)
## extent      : 304063.4, 304590.5, 4133379, 4134320  (xmin, xmax, ymin, ymax)
## coord. ref. : NA 
## values      : conductance 
## matrix class: dsCMatrix</code></pre>
<p>In using the transition function, you must either invert the distance matrix</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tr &lt;-<span class="st"> </span><span class="kw">transition</span>( <span class="dv">1</span><span class="op">/</span>pine, <span class="dt">transitionFunction =</span> mean, <span class="dt">directions=</span><span class="dv">4</span> )</code></pre></div>
<p>or you can invert the transitionFunction itself.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tr &lt;-<span class="st"> </span><span class="kw">transition</span>(pine, <span class="dt">transitionFunction =</span>  <span class="dv">1</span><span class="op">/</span>mean, <span class="dt">directions=</span><span class="dv">4</span> )</code></pre></div>
<p>After correcting, the <code>tr</code> object is a raster of class <code>TransistionLayer</code> whose values denote the conductance across the landscape</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tr</code></pre></div>
<pre><code>## class       : TransitionLayer 
## dimensions  : 941, 527, 495907  (nrow, ncol, ncell)
## resolution  : 1.000212, 1.000212  (x, y)
## extent      : 304063.4, 304590.5, 4133379, 4134320  (xmin, xmax, ymin, ymax)
## coord. ref. : NA 
## values      : conductance 
## matrix class: dsCMatrix</code></pre>
<p>The size of the data within the transition matrix is a bit telling about why it takes a bit of time to estimate these objects. The cost raster itself has 941 rows and 527 columns. The transition matrix, <code>tr</code>, has the values of conductance stored for all (well, almost all) pairs of points on that surface in a matrix with 495907 rows and columns. That is <code>rdim(tr@transitionMatrix)[1]^2</code> estimates! Again, this is why it is important to make sure you are working with raster extents that are sufficiently large to capture the area relevant to connectivity but not so large as to have areas that are irrelevant. Those irrelevant components of your landscape will still be used to estimate transition matrices!</p>
<p>The shortest paths can be visualized as</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">coords &lt;-<span class="st"> </span><span class="kw">cbind</span>( <span class="dt">x=</span><span class="kw">c</span>(<span class="dv">304374</span>,<span class="dv">304546</span>,<span class="dv">304079</span>),
                 <span class="dt">y=</span><span class="kw">c</span>(<span class="dv">4134281</span>,<span class="dv">4133413</span>,<span class="dv">4133584</span>))
pts &lt;-<span class="st"> </span><span class="kw">SpatialPoints</span>( coords )
path.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">shortestPath</span>( tr, pts[<span class="dv">1</span>], pts[<span class="dv">2</span>], <span class="dt">output=</span><span class="st">&quot;SpatialLines&quot;</span>)
path.<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">shortestPath</span>( tr, pts[<span class="dv">2</span>], pts[<span class="dv">3</span>], <span class="dt">output=</span><span class="st">&quot;SpatialLines&quot;</span>)
path.<span class="dv">3</span> &lt;-<span class="st"> </span><span class="kw">shortestPath</span>( tr, pts[<span class="dv">3</span>], pts[<span class="dv">1</span>], <span class="dt">output=</span><span class="st">&quot;SpatialLines&quot;</span>)
<span class="kw">plot</span>( pine )
<span class="kw">lines</span>( path.<span class="dv">1</span>, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>)
<span class="kw">lines</span>( path.<span class="dv">2</span>, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)
<span class="kw">lines</span>( path.<span class="dv">3</span>, <span class="dt">col=</span><span class="st">&quot;darkgreen&quot;</span>)
<span class="kw">points</span>( pts, <span class="dt">pch=</span><span class="dv">16</span>, <span class="dt">col=</span><span class="st">&quot;black&quot;</span>)</code></pre></div>
<p><img src="LGDA_files/figure-html/unnamed-chunk-167-1.png" width="672" /></p>
<p>The distances along those paths is estimated, in a pair-wise fashion, as</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">d.lcp &lt;-<span class="st"> </span><span class="kw">costDistance</span>(tr, pts) 
d.lcp</code></pre></div>
<pre><code>##           1         2
## 2 1045.1439          
## 3 1012.7618  659.2799</code></pre>
<p>which is exactly what we need for incorporating ecological separation into models of connectivity.</p>
<p>I should raise an important point here about the form of that matrix. The order of rows and columns follow the order of the coordinates that are passed to the <code>shortestPath</code> function. This will be the same order of stratum that you need to use for estimating both the other ecological/spatial distances as well the genetic distances. I find it helpful to add <code>rowname</code> and <code>colname</code> attributes to these matrices to make sure the orders are correct in subsequent analyses.</p>
</div>
<div id="all-paths-circuitscape-distances" class="section level3">
<h3><span class="header-section-number">3.4.2</span> All Paths (CircuitScape) Distances</h3>
<p>The All Paths distance is estimated using the same approaches as for the Least Cost Paths, a transition matrix should be created and corrected and SpatialPoints will be used to estimate separation. There are two main differences. First, the <code>geoCorrection</code> function, uses a different type of correction, set it to <code>type='r'</code> from <code>type='c'</code>. Next, the pairwise distance between these locations are estimated by <code>communteDistance</code> instead of <code>costDisance</code>.</p>
<p>Here is an example using the same points.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tr.ct &lt;-<span class="st"> </span><span class="kw">transition</span>( <span class="dv">1</span><span class="op">/</span>pine, <span class="dt">transitionFunction =</span> mean, <span class="dt">directions=</span><span class="dv">4</span> )
tr.ct &lt;-<span class="st"> </span><span class="kw">geoCorrection</span>( tr.ct, <span class="dt">type=</span><span class="st">&quot;r&quot;</span>, <span class="dt">multpl=</span><span class="ot">FALSE</span>, <span class="dt">scl=</span><span class="ot">FALSE</span>)
d.ct &lt;-<span class="st"> </span><span class="kw">commuteDistance</span>(tr.ct, pts)
d.ct</code></pre></div>
<pre><code>##         1       2
## 2 8085689        
## 3 7574426 6738172</code></pre>
<p>You can also estimate all paths distance using the program CircuitScape by Brad McRae. Circuitscape, a stand alone Java application and you should have downloaded it and have it on your computer. What we need to run it is the cost raster and the points you are using, also as a raster, saved in ascii format.</p>
<p>To demonstrate the use of CircuitScape, we will use a slightly larger data set for the point locations. This raster <strong>must</strong> be identical in both extent and granularity for the analysis to work. The function <code>rasterize</code> takes some points and a raster and returns a correctly scaled raster with the points indicated as the only non-<code>NA</code> pixels on the raster.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">trees &lt;-<span class="st"> </span><span class="kw">read.table</span>(<span class="st">&quot;./data/dogwood/tree_coords.txt&quot;</span>)
trees &lt;-<span class="st"> </span><span class="kw">SpatialPoints</span>( trees[,<span class="dv">2</span><span class="op">:</span><span class="dv">3</span>] )
trees_raster &lt;-<span class="st"> </span><span class="kw">rasterize</span>( <span class="dt">x=</span>trees, <span class="dt">y=</span>pines )
trees_raster</code></pre></div>
<pre><code>## class       : RasterLayer 
## dimensions  : 941, 527, 495907  (nrow, ncol, ncell)
## resolution  : 1.000212, 1.000212  (x, y)
## extent      : 304063.4, 304590.5, 4133379, 4134320  (xmin, xmax, ymin, ymax)
## coord. ref. : NA 
## data source : in memory
## names       : layer 
## values      : 1, 17  (min, max)</code></pre>
<p>We can write both of these rasters as ascii files.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">writeRaster</span>(trees_raster,<span class="st">&quot;trees_rast.asc&quot;</span>,<span class="dt">overwrite=</span><span class="ot">TRUE</span>)
<span class="kw">writeRaster</span>(pine,<span class="st">&quot;pine_rast.asc&quot;</span>,<span class="dt">overwrite=</span><span class="ot">TRUE</span>)</code></pre></div>
<p>Then start Circuitscape and set the following parameters:<br />
1. Choose Step 1: Raster 2. Choose Step 2: All pairs 3. Use the file section buttons to load in both the cost and site rasters. 4. Select an output location (it will create a lot of files), I called it ‘trees’ (the results are saved with that as a file prefix). 5. Selection the option to save a current map. 6. Hit Run.</p>
<p>It will take a bit of time, it has to estimate distances across all pairs of points. When it finishes, it will produce a lot of files, two of which we are interested in working with. The first is the circuit distance data file. There are two version of this file, one with distances in column format (<tt>trees_resistances_3columns</tt>) and the other as a matrix (<tt>trees_resistance</tt>). If you named the output location something other than ‘tree’, it will be prefixed with that name instead—it will be obvious due to the huge number of files that appeared in your folder which ones to look at.</p>
<p>The next file, which is much more interesting to look at, is a raster map of the current, as it was estimated across the landscape. Is should be saved as <tt>trees_cum_curmap.asc</tt> file. You can load that one as a normal raster.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pine.current &lt;-<span class="st"> </span><span class="kw">raster</span>(<span class="st">&quot;./spatial_data/trees_cum_curmap.asc&quot;</span>)</code></pre></div>
<p>The surface of the current raster is definitely not smooth. Here is a blown up region of the raster around some focal trees. The cumulative effect of all paths across the landscape make a rugose topology.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">e &lt;-<span class="st"> </span><span class="kw">extent</span>( <span class="kw">c</span>( <span class="dv">304421</span>, <span class="dv">304583</span>, <span class="dv">4133540</span>, <span class="dv">4133869</span>) )
pine.portion &lt;-<span class="st"> </span><span class="kw">crop</span>( pine.current, e )
df &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="kw">rasterToPoints</span>(pine.portion) )
<span class="kw">names</span>(df) &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;X&quot;</span>, <span class="st">&quot;Y&quot;</span>, <span class="st">&quot;Current&quot;</span>)
df<span class="op">$</span>Current &lt;-<span class="st"> </span><span class="kw">log</span>( df<span class="op">$</span>Current)
df<span class="op">$</span>Current[ df<span class="op">$</span>Current <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span> ] &lt;-<span class="st"> </span><span class="dv">0</span>
<span class="kw">ggplot</span>(df, <span class="kw">aes</span>(X,Y,<span class="dt">fill=</span>Current)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_tile</span>() <span class="op">+</span><span class="st"> </span><span class="kw">scale_fill_gradientn</span>( <span class="dt">colors=</span><span class="kw">c</span>(<span class="st">&#39;#a6611a&#39;</span>,<span class="st">&#39;#dfc27d&#39;</span>,<span class="st">&#39;#f5f5f5&#39;</span>,<span class="st">&#39;#80cdc1&#39;</span>,<span class="st">&#39;#018571&#39;</span>)) <span class="op">+</span><span class="st"> </span><span class="kw">coord_equal</span>()</code></pre></div>
<p><img src="LGDA_files/figure-html/unnamed-chunk-173-1.png" width="672" /></p>
</div>
<div id="logistical-issues" class="section level3">
<h3><span class="header-section-number">3.4.3</span> Logistical Issues</h3>
<p>Estimation of these values is not a rapid endeavor. For the relatively small raster we used in these examples and using only three points, the time to complete the estimation (in seconds) for both algorithms on my laptop was:</p>
<table>
<thead>
<tr class="header">
<th align="left">Algorithm</th>
<th align="right">K</th>
<th align="right">Duration</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Least Cost Path</td>
<td align="right">3</td>
<td align="right">11.773</td>
</tr>
<tr class="even">
<td align="left">All Path (CircuitScape)</td>
<td align="right">3</td>
<td align="right">17.765</td>
</tr>
</tbody>
</table>
<p>The CircuitScape algorithm takes a slightly different approach in estimating the distances than the <code>gdistance</code> and also takes a bit of time to run.</p>
</div>
<div id="pixel-size-and-path-lengths" class="section level3">
<h3><span class="header-section-number">3.4.4</span> Pixel Size and Path Lengths</h3>
<p>As mentioned in the context of remote sensing above, pixel size also influences both the path across the landscape as well as its magnitude.</p>
<p>Here we can estimate paths between the three example points measured on two different pixel sizes, 1x and 10x.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">tr1 &lt;-<span class="st"> </span><span class="kw">transition</span>( <span class="dv">1</span><span class="op">/</span>pine.p1, <span class="dt">transitionFunction =</span> mean, <span class="dt">directions=</span><span class="dv">4</span> )
tr1 &lt;-<span class="st"> </span><span class="kw">geoCorrection</span>( tr1, <span class="dt">type=</span><span class="st">&quot;c&quot;</span>, <span class="dt">multpl=</span><span class="ot">FALSE</span>, <span class="dt">scl=</span><span class="ot">FALSE</span>)
path.p11 &lt;-<span class="st"> </span><span class="kw">shortestPath</span>( tr1, pts[<span class="dv">1</span>], pts[<span class="dv">2</span>], <span class="dt">output=</span><span class="st">&quot;SpatialLines&quot;</span>)
path.p12 &lt;-<span class="st"> </span><span class="kw">shortestPath</span>( tr1, pts[<span class="dv">2</span>], pts[<span class="dv">3</span>], <span class="dt">output=</span><span class="st">&quot;SpatialLines&quot;</span>)
path.p13 &lt;-<span class="st"> </span><span class="kw">shortestPath</span>( tr1, pts[<span class="dv">3</span>], pts[<span class="dv">1</span>], <span class="dt">output=</span><span class="st">&quot;SpatialLines&quot;</span>)

tr2 &lt;-<span class="st"> </span><span class="kw">transition</span>( <span class="dv">1</span><span class="op">/</span>pine.p4, <span class="dt">transitionFunction =</span> mean, <span class="dt">directions=</span><span class="dv">4</span> )
tr2 &lt;-<span class="st"> </span><span class="kw">geoCorrection</span>( tr2, <span class="dt">type=</span><span class="st">&quot;c&quot;</span>, <span class="dt">multpl=</span><span class="ot">FALSE</span>, <span class="dt">scl=</span><span class="ot">FALSE</span>)
path.p21 &lt;-<span class="st"> </span><span class="kw">shortestPath</span>( tr2, pts[<span class="dv">1</span>], pts[<span class="dv">2</span>], <span class="dt">output=</span><span class="st">&quot;SpatialLines&quot;</span>)
path.p22 &lt;-<span class="st"> </span><span class="kw">shortestPath</span>( tr2, pts[<span class="dv">2</span>], pts[<span class="dv">3</span>], <span class="dt">output=</span><span class="st">&quot;SpatialLines&quot;</span>)
path.p23 &lt;-<span class="st"> </span><span class="kw">shortestPath</span>( tr2, pts[<span class="dv">3</span>], pts[<span class="dv">1</span>], <span class="dt">output=</span><span class="st">&quot;SpatialLines&quot;</span>)

<span class="kw">par</span>( <span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="dt">mar=</span><span class="kw">rep</span>(<span class="dv">1</span>,<span class="dv">4</span>))
<span class="kw">plot</span>( pine , <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)
<span class="kw">lines</span>( path.p11, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>)
<span class="kw">lines</span>( path.p12, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)
<span class="kw">lines</span>( path.p13, <span class="dt">col=</span><span class="st">&quot;darkgreen&quot;</span>)
<span class="kw">points</span>( pts, <span class="dt">pch=</span><span class="dv">16</span>, <span class="dt">col=</span><span class="st">&quot;black&quot;</span>)
<span class="kw">plot</span>( pine.p4 , <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)
<span class="kw">lines</span>( path.p21, <span class="dt">col=</span><span class="st">&quot;red&quot;</span>)
<span class="kw">lines</span>( path.p22, <span class="dt">col=</span><span class="st">&quot;blue&quot;</span>)
<span class="kw">lines</span>( path.p23, <span class="dt">col=</span><span class="st">&quot;darkgreen&quot;</span>)
<span class="kw">points</span>( pts, <span class="dt">pch=</span><span class="dv">16</span>, <span class="dt">col=</span><span class="st">&quot;black&quot;</span>)</code></pre></div>
<p><img src="LGDA_files/figure-html/unnamed-chunk-176-1.png" width="672" /></p>
<p>Increasing the coarseness also changes the overall separation of points on the landscape, inserting positive bias.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">d1 &lt;-<span class="st"> </span><span class="kw">as.matrix</span>( <span class="kw">costDistance</span>(tr1, trees) )
d2 &lt;-<span class="st"> </span><span class="kw">as.matrix</span>( <span class="kw">costDistance</span>(tr2, trees) )
df &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="dt">Diff =</span> d2[<span class="kw">lower.tri</span>(d2)] <span class="op">-</span><span class="st"> </span>d1[<span class="kw">lower.tri</span>(d1)] )
<span class="kw">ggplot</span>( df, <span class="kw">aes</span>( Diff ) ) <span class="op">+</span><span class="st"> </span><span class="kw">geom_histogram</span>(<span class="dt">bins=</span><span class="dv">30</span>) <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;Difference in Path Lengths&quot;</span>)</code></pre></div>
<p><img src="LGDA_files/figure-html/unnamed-chunk-177-1.png" width="672" /></p>
<p>Unfortunately, there is no way, <em>a priori</em> what the proper pixel size should be, only the data can give suggestions.</p>
</div>
<div id="scaling-resistance" class="section level3">
<h3><span class="header-section-number">3.4.5</span> Scaling Resistance</h3>
<p>In our examples thus far, we have assumed that the presence feature of interest was twice as costly to traverse than the landscape outside the feature. The <code>pine</code> raster has a <span class="math inline">\(1.0\)</span> where there is no conifer canopy and a value of <span class="math inline">\(2.0\)</span> under the pine trees. However, there is no <em>a priori</em> reason why this is the correct scaling of cost as it pertains to the movement of pollen—it could just as easily be 1:10 or 1:100. It could also be, as in the first figure above that the cost is accumulated for <em>not</em> moving under the conifer canopy, in which it would be a ratio of 2:1, 10:1, or 100:1. If we do not have a biologically motivated reason for assigning specific values to cost resistance, it is probably best to examine a range of potential values and let the genetic data provide suggestions regarding which would be the most explanatory.</p>
<p>Scaling matrices can be done as either statically scaling the values or by allowing the values in neighboring cells to influence each other, similar to say neighborhood effects.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">pine.<span class="dv">2</span> &lt;-<span class="st"> </span>pine
pine.<span class="dv">5</span> &lt;-<span class="st"> </span>( pine <span class="op">-</span><span class="st"> </span><span class="dv">1</span> ) <span class="op">*</span><span class="st"> </span><span class="dv">4</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
pine.<span class="dv">10</span> &lt;-<span class="st"> </span>( pine <span class="op">-</span><span class="st"> </span><span class="dv">1</span> ) <span class="op">*</span><span class="st"> </span><span class="dv">9</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
pine.<span class="dv">100</span> &lt;-<span class="st"> </span>( pine <span class="op">-</span><span class="st"> </span><span class="dv">1</span> ) <span class="op">*</span><span class="st"> </span><span class="dv">99</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
<span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">2</span>,<span class="dv">2</span>), <span class="dt">mai=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>))
<span class="kw">plot</span>(pine.<span class="dv">2</span>, <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)
<span class="kw">plot</span>(pine.<span class="dv">5</span>, <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)
<span class="kw">plot</span>(pine.<span class="dv">10</span>, <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)
<span class="kw">plot</span>(pine.<span class="dv">100</span>, <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)</code></pre></div>
<p><img src="LGDA_files/figure-html/unnamed-chunk-178-1.png" width="672" /></p>
<p>Smoothing is a way to modifying cells of a raster based upon the immediate neighbors. In this case, we can take the average of the eight surrounding cells and apply that value to the center cell. The focal function take the target raster, a 3x3 matrix of values indicating the amount each of the neighboring cells contribute to the characteristics of the target cell, and a function to use to determine the value assigned to the central cell. In this case, we use <code>mean</code>, though you could use max or other user defined functions. The net effect of this approach is to take the ‘rough edges’ out of the raster and smooth the transitions. It also expands the spatial extent of the feature into surrounding cell.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">w &lt;-<span class="st"> </span><span class="kw">matrix</span>( <span class="dv">1</span>, <span class="dt">nrow=</span><span class="dv">3</span>, <span class="dt">ncol=</span><span class="dv">3</span>)
pine.smooth &lt;-<span class="st"> </span><span class="kw">focal</span>( pine.<span class="dv">2</span> , w , <span class="dt">fun=</span>mean)
<span class="kw">par</span>(<span class="dt">mfrow=</span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>), <span class="dt">mai=</span><span class="kw">c</span>(<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>))
<span class="kw">plot</span>( pine.<span class="dv">2</span>, <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span>)
<span class="kw">plot</span>( pine.smooth, <span class="dt">legend=</span><span class="ot">FALSE</span>, <span class="dt">axes=</span><span class="ot">FALSE</span> )</code></pre></div>
<p><img src="LGDA_files/figure-html/unnamed-chunk-179-1.png" width="672" /></p>
</div>
<div id="final-thoughts-on-raster-manipulations" class="section level3">
<h3><span class="header-section-number">3.4.6</span> Final Thoughts on Raster Manipulations</h3>
<p>The granularity, scale, cost, algorithm, and scaling of rasters that best describe the observed genetic structure are most likely the ones that we can designate as the most ‘biologically meaningful.’ How we determine which of the many potential combinations is actually the most relevant depends upon fitting the distance matrices to the genetic data.</p>
</div>
</div>
<div id="resistance-models-1" class="section level2">
<h2><span class="header-section-number">3.5</span> Resistance Models</h2>
<p>Once we have a set of candidate loci, we can then start the analyses. There are several ways to evaluate these matrices, most of which are based upon looking for systematic changes in genetic distance that correspond with changes in one or more of the predictor raster distances.</p>
<div id="the-mantel-test" class="section level3">
<h3><span class="header-section-number">3.5.1</span> The Mantel Test</h3>
<p>One of the most common approaches to evaluating the extent to which resistance distances are correlated with genetic distances is via the Mantel Test. It estimates a parameter, <span class="math inline">\(Z\)</span>, as the element-wise product of both matrices.</p>
<p><span class="math display">\[
Z = \sum_{i=1}^N\sum_{j=1}^N x_{ij}*y_{ij}
\]</span></p>
<p>and then invokes the null hypothesis, <span class="math inline">\(H_O:\)</span><em>The values in the matrices are independent</em>. If this is true then large values in <span class="math inline">\(\mathbf{X}\)</span> should be randomly associated with all the values in <span class="math inline">\(\mathbf{Y}\)</span>. However, if there is an association than large values in one matrix may be associated with large ones in the other (for a positive correlation) or small in one may be associated with large in another (for a negative correlation). If <span class="math inline">\(H_O\)</span> is true, then any permutation of <span class="math inline">\(\mathbf{X}\)</span> and a re-estimation of <span class="math inline">\(Z\)</span> should produce values as large (or small) as the observed <span class="math inline">\(Z\)</span> value. Sounds simple, no? It also estimates a correlation coefficient, the default is a Pearson Product Moment though you can specify Spearman’s <span class="math inline">\(\rho\)</span> or Kendall’s <span class="math inline">\(\tau\)</span> as well. There are a few different implementations of the Mantel, the one I’m using below is the one from the <em>vegan</em> library. Here is the documentation for the function that provides a bit more information.</p>
<div class="scrollingbox">
<pre>
mantel {vegan}  R Documentation
Mantel and Partial Mantel Tests for Dissimilarity Matrices

Description

Function mantel finds the Mantel statistic as a matrix correlation between two dissimilarity matrices, and function mantel.partial finds the partial Mantel statistic as the partial matrix correlation between three dissimilarity matrices. The significance of the statistic is evaluated by permuting rows and columns of the first dissimilarity matrix.

Usage

mantel(xdis, ydis, method="pearson", permutations=999, strata = NULL,
    na.rm = FALSE, parallel = getOption("mc.cores"))
mantel.partial(xdis, ydis, zdis, method = "pearson", permutations = 999, 
    strata = NULL, na.rm = FALSE, parallel = getOption("mc.cores"))
Arguments

xdis, ydis, zdis    
Dissimilarity matrices or a dist objects.
method  
Correlation method, as accepted by cor: "pearson", "spearman" or "kendall".
permutations    
a list of control values for the permutations as returned by the function how, or the number of permutations required, or a permutation matrix where each row gives the permuted indices.
strata  
An integer vector or factor specifying the strata for permutation. If supplied, observations are permuted only within the specified strata.
na.rm   
Remove missing values in calculation of Mantel correlation. Use this option with care: Permutation tests can be biased, in particular if two matrices had missing values in matching positions.
parallel    
Number of parallel processes or a predefined socket cluster. With parallel = 1 uses ordinary, non-parallel processing. The parallel processing is done with parallel package.
Details

Mantel statistic is simply a correlation between entries of two dissimilarity matrices (some use cross products, but these are linearly related). However, the significance cannot be directly assessed, because there are N(N-1)/2 entries for just N observations. Mantel developed asymptotic test, but here we use permutations of N rows and columns of dissimilarity matrix. See permutations for additional details on permutation tests in Vegan.

Partial Mantel statistic uses partial correlation conditioned on the third matrix. Only the first matrix is permuted so that the correlation structure between second and first matrices is kept constant. Although mantel.partial silently accepts other methods than "pearson", partial correlations will probably be wrong with other methods.

The function uses cor, which should accept alternatives pearson for product moment correlations and spearman or kendall for rank correlations.

Value

The function returns a list of class mantel with following components:

Call    
Function call.
method  
Correlation method used, as returned by cor.test.
statistic   
The Mantel statistic.
signif  
Empirical significance level from permutations.
perm    
A vector of permuted values. The distribution of permuted values can be inspected with permustats function.
permutations    
Number of permutations.
control 
A list of control values for the permutations as returned by the function how.
Note

Legendre & Legendre (2012, Box 10.4) warn against using partial Mantel correlations.

Author(s)

Jari Oksanen

References

The test is due to Mantel, of course, but the current implementation is based on Legendre and Legendre.

Legendre, P. and Legendre, L. (2012) Numerical Ecology. 3rd English Edition. Elsevier.

See Also

cor for correlation coefficients, protest (“Procrustes test”) for an alternative with ordination diagrams, anosim and mrpp for comparing dissimilarities against classification. For dissimilarity matrices, see vegdist or dist. See bioenv for selecting environmental variables.

Examples

## Is vegetation related to environment?
data(varespec)
data(varechem)
veg.dist <- vegdist(varespec) # Bray-Curtis
env.dist <- vegdist(scale(varechem), "euclid")
mantel(veg.dist, env.dist)
mantel(veg.dist, env.dist, method="spear")
[Package vegan version 2.4-0 Index]</pre>
</div>
<p>Since it takes a bit of time to extract the distance matrices from the rasters, we have provided some pre-configured distance matrices for the trees identified above. These rasters are located in the <tt>data/dogwood</tt> folder. For these rasters we estimate cost distance across a range of values representing both avoidance (10:1, 7:1, 5:1, and 2:1) and preference (1:2, 1:5, 1:7 1:10) of the feature.</p>
<p>Each distance matrix is in a single file, the name of which records the algorithm (lcp vs. ct), the feature (cf, cv, rd, fd, mh from above), and the costs of <tt>out.in</tt>. For example, the file <tt>ct.cf.1.5.rda</tt> is the Circuit Theory, <em>Cornus florida</em> feature with costs of 1 in the feature and 5 outside of it.</p>
<p>In the following code, I loop through the files estimated using the least cost path approach (<code>pattern='lcp*'</code>). For each file, I break apart the file name and record the feature type, the in cost, the out cost, the algorithm used to estimate distances, and the correlation.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">lcp.files &lt;-<span class="st"> </span><span class="kw">list.files</span>(<span class="st">&quot;./data/dogwood/&quot;</span>, <span class="dt">pattern=</span><span class="st">&quot;lcp*&quot;</span>, <span class="dt">full.names =</span> <span class="ot">TRUE</span>)
<span class="kw">library</span>(vegan)
df &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="dt">File=</span>lcp.files,
                  <span class="dt">Feature=</span><span class="ot">NA</span>,
                  <span class="dt">In=</span><span class="ot">NA</span>,
                  <span class="dt">Out=</span><span class="ot">NA</span>,
                  <span class="dt">Type=</span><span class="st">&quot;Least Cost&quot;</span>,
                  <span class="dt">Correlation=</span><span class="ot">NA</span>, 
                  <span class="dt">P=</span><span class="ot">NA</span>)
<span class="kw">load</span>( <span class="st">&quot;./data/dogwood/G.rda&quot;</span>)
<span class="cf">for</span>( path <span class="cf">in</span> lcp.files) {
  file &lt;-<span class="st"> </span><span class="kw">strsplit</span>( path, <span class="dt">split=</span><span class="st">&quot;/&quot;</span>)[[<span class="dv">1</span>]][<span class="dv">5</span>]
  components &lt;-<span class="st"> </span><span class="kw">strsplit</span>(file, <span class="dt">split=</span><span class="st">&quot;.&quot;</span>,<span class="dt">fixed=</span><span class="ot">TRUE</span>)[[<span class="dv">1</span>]]
  <span class="kw">load</span>( path )
  fit &lt;-<span class="st"> </span><span class="kw">mantel</span>( <span class="kw">as.dist</span>( G ), <span class="kw">as.dist</span>( D ))
  idx &lt;-<span class="st"> </span><span class="kw">which</span>( df<span class="op">$</span>File <span class="op">==</span><span class="st"> </span>path)
  df<span class="op">$</span>Feature[idx] &lt;-<span class="st"> </span>components[<span class="dv">2</span>]
  df<span class="op">$</span>In[idx] &lt;-<span class="st"> </span><span class="kw">as.numeric</span>( components[<span class="dv">3</span>] )
  df<span class="op">$</span>Out[idx] &lt;-<span class="st"> </span><span class="kw">as.numeric</span>( components[<span class="dv">4</span>] )
  df<span class="op">$</span>Correlation[idx] &lt;-<span class="st"> </span>fit<span class="op">$</span>statistic
  df<span class="op">$</span>P[idx] &lt;-<span class="st"> </span>fit<span class="op">$</span>signif
}
<span class="kw">library</span>(DT)
<span class="kw">datatable</span>(df[,<span class="dv">2</span><span class="op">:</span><span class="dv">7</span>])</code></pre></div>
<div id="htmlwidget-7b8f3d0c861f7dc2e0b7" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-7b8f3d0c861f7dc2e0b7">{"x":{"filter":"none","data":[["1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44"],["cf","cf","cf","cf","cf","cf","cf","cf","cv","cv","cv","cv","cv","cv","cv","cv","elevation","elevation","euclidian","euclidian","fd","fd","fd","fd","fd","fd","fd","fd","mh","mh","mh","mh","mh","mh","mh","mh","rd","rd","rd","rd","rd","rd","rd","rd"],[1,1,1,1,10,2,5,7,1,1,1,1,10,2,5,7,1,null,1,null,1,1,1,1,10,2,5,7,1,1,1,1,10,2,5,7,1,1,1,1,10,2,5,7],[10,2,5,7,1,1,1,1,10,2,5,7,1,1,1,1,1,null,1,null,10,2,5,7,1,1,1,1,10,2,5,7,1,1,1,1,10,2,5,7,1,1,1,1],["Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost","Least Cost"],[0.510720309175223,0.512594140710916,0.511362024968477,0.511004802487507,0.515122641592962,0.512975829977014,0.514070305042238,0.514599705909336,0.482309877353384,0.504522570769721,0.491572522145399,0.48574488488042,0.529533122171948,0.51542540696562,0.522472961435365,0.526730110419117,0.528658441781566,0.528658441781566,0.518153125821159,0.518153125821159,0.50524204193857,0.510515883376434,0.507035230151978,0.506046234010779,0.50971464670278,0.509768754772097,0.509728564418161,0.509720123650034,0.481693875751585,0.50656484714998,0.493248433539043,0.488087445323018,0.52965015871813,0.514874598726828,0.529242640319228,0.530059705807836,0.502854503791509,0.50948876385378,0.507461185611065,0.504737544389389,0.512745840823682,0.513173958681788,0.512999098314619,0.512905475637799],[0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001,0.001]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>Feature<\/th>\n      <th>In<\/th>\n      <th>Out<\/th>\n      <th>Type<\/th>\n      <th>Correlation<\/th>\n      <th>P<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[2,3,5,6]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p>For any given feature, we have many different estimates of the correlation as the relative raster costs were varied across values of of 10:1, 7:1, 5:1, 2:1, 1:2, 5:1 7:1, 10:1. I plot the x-axis along a log10 scale to make the dispersion along the horizontal axis a bit more regular.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df &lt;-<span class="st"> </span>df[ <span class="op">!</span>(df<span class="op">$</span>Feature <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;elevation&quot;</span>,<span class="st">&quot;euclidian&quot;</span>)),]
df<span class="op">$</span>Feature &lt;-<span class="st"> </span><span class="kw">factor</span>( df<span class="op">$</span>Feature )
df<span class="op">$</span>Ratio &lt;-<span class="st"> </span><span class="kw">log10</span>( df<span class="op">$</span>In <span class="op">/</span><span class="st"> </span>df<span class="op">$</span>Out )
df &lt;-<span class="st"> </span><span class="kw">droplevels</span>(df)
<span class="kw">ggplot</span>( df, <span class="kw">aes</span>(<span class="dt">x=</span>Ratio, <span class="dt">y=</span>Correlation, <span class="dt">color=</span>Feature)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;Log(In:Out)&quot;</span>)</code></pre></div>
<p><img src="LGDA_files/figure-html/unnamed-chunk-181-1.png" width="672" /></p>
<p>Compared as a whole, we see that some features change very little across the landscape (<em>cf</em>, <em>rd</em>, and <em>fd</em>) while others clearly do a better job of explaining genetic covariance (<em>mh</em> and <em>cv</em>). These observations suggest that a feature like <em>mh</em> with a cost of 7x more in the feature as outside of it. We can see the best model as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">load</span>(<span class="st">&quot;data/dogwood/lcp.mh.7.1.rda&quot;</span>)
MH &lt;-<span class="st"> </span>D
fit.mh &lt;-<span class="st"> </span><span class="kw">mantel</span>( <span class="kw">as.dist</span>(G), <span class="kw">as.dist</span>(MH), <span class="dt">permutations =</span> <span class="dv">10000</span> )
fit.mh</code></pre></div>
<pre><code>## 
## Mantel statistic based on Pearson&#39;s product-moment correlation 
## 
## Call:
## mantel(xdis = as.dist(G), ydis = as.dist(MH), permutations = 10000) 
## 
## Mantel statistic r: 0.5301 
##       Significance: 9.999e-05 
## 
## Upper quantiles of permutations (null model):
##   90%   95% 97.5%   99% 
## 0.114 0.160 0.199 0.249 
## Permutation: free
## Number of permutations: 10000</code></pre>
</div>
<div id="the-partial-mantel" class="section level3">
<h3><span class="header-section-number">3.5.2</span> The Partial Mantel</h3>
<p>In the previous example, we examined the correlation in only one feature at a time. The partial Mantel test extends this approach to fit one feature and then estimate the conditional correlation of the second one on the genetic distances providing an indication of two-way relationships. Using the same approach as before, we iterate through the remaining features and estimate the partial correlation coefficient after conditioning on the <em>mh</em> raster.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">target &lt;-<span class="st"> </span>lcp.files[ <span class="dv">34</span> ]
remaining &lt;-<span class="st"> </span>lcp.files[ <span class="op">-</span>(<span class="dv">27</span><span class="op">:</span><span class="dv">34</span>) ]
dfp &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="dt">File=</span>remaining,
                  <span class="dt">Feature=</span><span class="ot">NA</span>,
                  <span class="dt">In=</span><span class="ot">NA</span>,
                  <span class="dt">Out=</span><span class="ot">NA</span>,
                  <span class="dt">Type=</span><span class="st">&quot;Least Cost&quot;</span>,
                  <span class="dt">Correlation=</span><span class="ot">NA</span>, 
                  <span class="dt">P=</span><span class="ot">NA</span>)

<span class="cf">for</span>( path <span class="cf">in</span> remaining) {
  file &lt;-<span class="st"> </span><span class="kw">strsplit</span>( path, <span class="dt">split=</span><span class="st">&quot;/&quot;</span>)[[<span class="dv">1</span>]][<span class="dv">5</span>]
  components &lt;-<span class="st"> </span><span class="kw">strsplit</span>(file, <span class="dt">split=</span><span class="st">&quot;.&quot;</span>,<span class="dt">fixed=</span><span class="ot">TRUE</span>)[[<span class="dv">1</span>]]
  <span class="kw">load</span>( path )
  fit &lt;-<span class="st"> </span><span class="kw">mantel.partial</span>(<span class="kw">as.dist</span>(G), <span class="kw">as.dist</span>(MH), <span class="kw">as.dist</span>(D))

  idx &lt;-<span class="st"> </span><span class="kw">which</span>( dfp<span class="op">$</span>File <span class="op">==</span><span class="st"> </span>path)
  dfp<span class="op">$</span>Feature[idx] &lt;-<span class="st"> </span>components[<span class="dv">2</span>]
  dfp<span class="op">$</span>In[idx] &lt;-<span class="st"> </span><span class="kw">as.numeric</span>( components[<span class="dv">3</span>] )
  dfp<span class="op">$</span>Out[idx] &lt;-<span class="st"> </span><span class="kw">as.numeric</span>( components[<span class="dv">4</span>] )
  dfp<span class="op">$</span>Correlation[idx] &lt;-<span class="st"> </span>fit<span class="op">$</span>statistic
  dfp<span class="op">$</span>P[idx] &lt;-<span class="st"> </span>fit<span class="op">$</span>signif
}
dfp &lt;-<span class="st"> </span>dfp[ <span class="op">!</span>(dfp<span class="op">$</span>Feature <span class="op">%in%</span><span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;elevation&quot;</span>,<span class="st">&quot;euclidian&quot;</span>)),]
dfp<span class="op">$</span>Feature &lt;-<span class="st"> </span><span class="kw">factor</span>( dfp<span class="op">$</span>Feature )
dfp<span class="op">$</span>Ratio &lt;-<span class="st"> </span><span class="kw">log10</span>( dfp<span class="op">$</span>In <span class="op">/</span><span class="st"> </span>dfp<span class="op">$</span>Out )
dfp &lt;-<span class="st"> </span><span class="kw">droplevels</span>(dfp)
<span class="kw">ggplot</span>( dfp, <span class="kw">aes</span>(<span class="dt">x=</span>Ratio, <span class="dt">y=</span>Correlation, <span class="dt">color=</span>Feature)) <span class="op">+</span><span class="st"> </span><span class="kw">geom_line</span>() <span class="op">+</span><span class="st"> </span><span class="kw">geom_point</span>() <span class="op">+</span><span class="st"> </span><span class="kw">xlab</span>(<span class="st">&quot;Log(In:Out)&quot;</span>)</code></pre></div>
<p><img src="LGDA_files/figure-html/unnamed-chunk-183-1.png" width="672" /></p>
<p>From these results, we would conclude that both <em>mh</em> and <em>cv</em> are the best features we examined.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">load</span>(<span class="st">&quot;data/dogwood/lcp.cv.1.10.rda&quot;</span>)
CV &lt;-<span class="st"> </span>D
fit &lt;-<span class="st"> </span><span class="kw">mantel.partial</span>(<span class="kw">as.dist</span>(G), <span class="kw">as.dist</span>(MH), <span class="kw">as.dist</span>(CV), <span class="dt">permutations =</span> <span class="dv">10000</span>)
fit</code></pre></div>
<pre><code>## 
## Partial Mantel statistic based on Pearson&#39;s product-moment correlation 
## 
## Call:
## mantel.partial(xdis = as.dist(G), ydis = as.dist(MH), zdis = as.dist(CV),      permutations = 10000) 
## 
## Mantel statistic r: 0.2532 
##       Significance: 0.0087991 
## 
## Upper quantiles of permutations (null model):
##   90%   95% 97.5%   99% 
## 0.128 0.168 0.202 0.246 
## Permutation: free
## Number of permutations: 10000</code></pre>
</div>
<div id="distance-regression" class="section level3">
<h3><span class="header-section-number">3.5.3</span> Distance Regression</h3>
<p>A direct extension of the Mantel test (in the same way a linear regression is an extension of a correlation) is are methods for multiple regression on distance matrices. The most commonly used implementation is that provided by the <em>ecodist</em> library.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(ecodist)</code></pre></div>
<p>The main difficulty in using multiple regression on distance (and Mantel as well) is to know the proper way to ascertain probabilities. Both rely upon permutations approaches, though knowing what level or what combinations of data to permute becomes problematic for all but the most simplistic model specifications. Here is the documentation for the MRM function, the one that actually fits the model and assesses the significance.</p>
<div class="scrollingbox">
<pre>
<pre>MRM {ecodist}  R Documentation
Multiple Regression on distance Matrices

Description

Multiple regression on distance matrices (MRM) using permutation tests of significance for regression coefficients and R-squared.

Usage

MRM(formula = formula(data), data = sys.parent(), nperm = 1000, mrank = FALSE)
Arguments

formula 
formula in R/S-Plus format describing the test to be conducted.
data    
an optional dataframe containing the variables in the model as columns of dissimilarities. By default the variables are taken from the current environment.
nperm   
number of permutations to use. If set to 0, the permutation test will be omitted.
mrank   
if this is set to FALSE (the default option), Pearson correlations will be used. If set to TRUE, the Spearman correlation (correlation ranked distances) will be used.
Details

Performs multiple regression on distance matrices following the methods outlined in Legendre et al. 1994.

Value

coef    
A matrix with regression coefficients and associated p-values from the permutation test (using the pseudo-t of Legendre et al. 1994).
r.squared   
Regression R-squared and associated p-value from the permutation test.
F.test  
F-statistic and p-value for overall F-test for lack of fit.
Author(s)

Sarah Goslee, Sarah.Goslee@ars.usda.gov

References

Lichstein, J. 2007. Multiple regression on distance matrices: A multivariate spatial analysis tool. Plant Ecology 188: 117-131.

Legendre, P.; Lapointe, F. and Casgrain, P. 1994. Modeling brain evolution from behavior: A permutational regression approach. Evolution 48: 1487-1499.

See Also

mantel

Examples

data(graze)
LOAR10.mrm <- MRM(dist(LOAR10) ~ dist(sitelocation) + dist(forestpct), data=graze, nperm=100)
[Package ecodist version 1.2.9 Index]</pre>
</div>
<p>Building upon the previous example, we can build up a MRM regression model, first fitting <em>mh</em> with a resistance of 7:1 to the genetic data.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">load</span>(<span class="st">&quot;data/dogwood/lcp.mh.7.1.rda&quot;</span>)
X1 &lt;-<span class="st"> </span>D
model.<span class="dv">1</span> &lt;-<span class="st"> </span><span class="kw">MRM</span>( <span class="kw">dist</span>(G) <span class="op">~</span><span class="st"> </span><span class="kw">dist</span>(X1) )
model.<span class="dv">1</span></code></pre></div>
<pre><code>## $coef
##               dist(G)  pval
## Int      1.800108e+01 0.828
## dist(X1) 5.317367e-05 0.001
## 
## $r.squared
##        R2      pval 
## 0.3801074 0.0010000 
## 
## $F.test
##        F   F.pval 
## 82.16647  0.00100</code></pre>
<p>There are no built-in diagnostics for MRM model types, what is object that is returned from the function is simply a list object with those values in it. The MRM function uses a permutation scheme, implemented in C, to determine significance of the model, of the <span class="math inline">\(R^2\)</span> term and of individual terms entered into the model.</p>
<p>Model development is done by hand using MRM, building up the regression manually. There are no automated facilities for forward or reverse term selection as there are for models derived from the <code>lm()</code> family of analyses. Unfortunately, there are also no ways of checking leverage and fit either. These facilities need to be developed to bring these methodologies up to par with other regression fitting routines in R.</p>
<p>After fitting the first term, we then examine the properties of the model after fitting the second term we identified using partial mantel.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">load</span>(<span class="st">&quot;data/dogwood/lcp.cv.10.1.rda&quot;</span>)
X2 &lt;-<span class="st"> </span>D
model.<span class="dv">2</span> &lt;-<span class="st"> </span><span class="kw">MRM</span>( <span class="kw">dist</span>(G) <span class="op">~</span><span class="st"> </span><span class="kw">dist</span>(X1) <span class="op">+</span><span class="st"> </span><span class="kw">dist</span>(X2)  )
model.<span class="dv">2</span></code></pre></div>
<pre><code>## $coef
##               dist(G)  pval
## Int      1.789979e+01 0.885
## dist(X1) 4.311454e-05 0.042
## dist(X2) 1.360215e-05 0.632
## 
## $r.squared
##        R2      pval 
## 0.3813608 0.0010000 
## 
## $F.test
##      F F.pval 
## 40.994  0.001</code></pre>
<p>From the output, we see that the probability associated with <span class="math inline">\(X2\)</span> does not suggest that this is adding significantly to the explanation of the genetic data. This suggests that in terms of developing a linear model with these data, could be defined spatially by making the mixed hardwoods raster 7:1 then fitting in the intercept and slope term from <code>model.1</code>, creating the expected connectivity cost raster.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">load</span>(<span class="st">&quot;data/dogwood/mixedhardwoods.rda&quot;</span>)
mh &lt;-<span class="st"> </span>mh <span class="op">*</span><span class="st"> </span><span class="dv">6</span> <span class="op">+</span><span class="st"> </span><span class="dv">1</span>
mh &lt;-<span class="st"> </span>model.<span class="dv">1</span><span class="op">$</span>coef[<span class="dv">1</span>,<span class="dv">1</span>] <span class="op">+</span><span class="st"> </span>mh <span class="op">*</span><span class="st"> </span>model.<span class="dv">1</span><span class="op">$</span>coef[<span class="dv">2</span>,<span class="dv">1</span>] 
df &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="kw">rasterToPoints</span>( mh ) )
<span class="kw">ggplot</span>( df, <span class="kw">aes</span>(<span class="dt">x=</span>x,<span class="dt">y=</span>y,<span class="dt">fill=</span>layer)) <span class="op">+</span><span class="st"> </span>
<span class="st">  </span><span class="kw">geom_tile</span>() <span class="op">+</span><span class="st"> </span><span class="kw">coord_equal</span>() <span class="op">+</span>
<span class="st">  </span><span class="kw">scale_fill_gradient</span>(<span class="dt">low=</span><span class="st">&quot;#f7fcfd&quot;</span>,<span class="dt">high=</span><span class="st">&quot;#00441b&quot;</span>) </code></pre></div>
<p><img src="LGDA_files/figure-html/unnamed-chunk-188-1.png" width="672" /></p>
</div>
<div id="model-comparisons-concerns" class="section level3">
<h3><span class="header-section-number">3.5.4</span> Model Comparisons &amp; Concerns</h3>
<p>Both the Mantel and the MRM approaches have been recently criticized in the literature due to some problems associated with assessing probabilities and ascertaining parameters like AIC, BIC, and DIC. At present, none of these methods can be applied to Mantel and partial Mantel approaches, so we are left with making decisions about alternatives based upon the magnitude of the correlation statistic and the probability associated with the null hypothesis.</p>
<p>In the literature, you can find examples of people trying to use AIC with MRM-l models (I confess, I am one of them). The statistic AIC is defined as</p>
<p><span class="math display">\[
AIC = -2ln(L) + 2k
\]</span></p>
<p>where <span class="math inline">\(L\)</span> is the maximum likelihood of the model and <span class="math inline">\(k\)</span> is the number of fit parameters. A model fit using <code>MRM()</code> does not have the ability to provide an estimate of <span class="math inline">\(L\)</span>.</p>
</div>
</div>
<div id="questions-2" class="section level2">
<h2><span class="header-section-number">3.6</span> Questions</h2>
<p>Here are some questions for you to exercise what was covered in the lab above.</p>
<ol style="list-style-type: decimal">
<li>For the cost networks, I only calculated the costs associated with least cost paths. Go back and load in the circuit theory paths and perform the same set of Mantel tests. For each feature, which combination of resistance value and distance algorithm produce the highest correlations?</li>
<li>To what extent does the pixel size influence hypothesized connectivity currents across the landscape? Select one of the aggregated pine rasters (pine.p1, pine.p2, or pine.p3) and run it through Circuitscape. Compare it to the output from the least cost distances.</li>
<li>The LiDAR data is at a much finer resolution than the rasters used to develop the models above. Using the medium vegetation layer, a slice through the forest understory thought to represent the spaces through which the pollinators actually move, and explore how granularity and raster magnitude influence the ability to describe genetic covariance.</li>
</ol>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="genetic-data.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="space-networks.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"history": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "";
    if (src === "" || src === "true") src = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(src))
      src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
