<!DOCTYPE html>
<html >

<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>Landscape Genetic Data Analysis</title>
  <meta name="description" content="A textbook for the use of R in spatial genetic data analysis.">
  <meta name="generator" content="bookdown 0.5 and GitBook 2.6.7">

  <meta property="og:title" content="Landscape Genetic Data Analysis" />
  <meta property="og:type" content="book" />
  
  
  <meta property="og:description" content="A textbook for the use of R in spatial genetic data analysis." />
  <meta name="github-repo" content="dyerlab/AMG" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Landscape Genetic Data Analysis" />
  
  <meta name="twitter:description" content="A textbook for the use of R in spatial genetic data analysis." />
  

<meta name="author" content="Rodney J. Dyer">



  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  
  
<link rel="prev" href="adaptive-landscape-genetics.html">
<link rel="next" href="references-cited.html">
<script src="libs/jquery-2.2.3/jquery.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />









<style type="text/css">
div.sourceCode { overflow-x: auto; }
table.sourceCode, tr.sourceCode, td.lineNumbers, td.sourceCode {
  margin: 0; padding: 0; vertical-align: baseline; border: none; }
table.sourceCode { width: 100%; line-height: 100%; background-color: #f8f8f8; }
td.lineNumbers { text-align: right; padding-right: 4px; padding-left: 4px; color: #aaaaaa; border-right: 1px solid #aaaaaa; }
td.sourceCode { padding-left: 5px; }
pre, code { background-color: #f8f8f8; }
code > span.kw { color: #204a87; font-weight: bold; } /* Keyword */
code > span.dt { color: #204a87; } /* DataType */
code > span.dv { color: #0000cf; } /* DecVal */
code > span.bn { color: #0000cf; } /* BaseN */
code > span.fl { color: #0000cf; } /* Float */
code > span.ch { color: #4e9a06; } /* Char */
code > span.st { color: #4e9a06; } /* String */
code > span.co { color: #8f5902; font-style: italic; } /* Comment */
code > span.ot { color: #8f5902; } /* Other */
code > span.al { color: #ef2929; } /* Alert */
code > span.fu { color: #000000; } /* Function */
code > span.er { color: #a40000; font-weight: bold; } /* Error */
code > span.wa { color: #8f5902; font-weight: bold; font-style: italic; } /* Warning */
code > span.cn { color: #000000; } /* Constant */
code > span.sc { color: #000000; } /* SpecialChar */
code > span.vs { color: #4e9a06; } /* VerbatimString */
code > span.ss { color: #4e9a06; } /* SpecialString */
code > span.im { } /* Import */
code > span.va { color: #000000; } /* Variable */
code > span.cf { color: #204a87; font-weight: bold; } /* ControlFlow */
code > span.op { color: #ce5c00; font-weight: bold; } /* Operator */
code > span.pp { color: #8f5902; font-style: italic; } /* Preprocessor */
code > span.ex { } /* Extension */
code > span.at { color: #c4a000; } /* Attribute */
code > span.do { color: #8f5902; font-weight: bold; font-style: italic; } /* Documentation */
code > span.an { color: #8f5902; font-weight: bold; font-style: italic; } /* Annotation */
code > span.cv { color: #8f5902; font-weight: bold; font-style: italic; } /* CommentVar */
code > span.in { color: #8f5902; font-weight: bold; font-style: italic; } /* Information */
</style>

<link rel="stylesheet" href="media/style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Frontmatter</a></li>
<li class="chapter" data-level="1" data-path="spatial-data.html"><a href="spatial-data.html"><i class="fa fa-check"></i><b>1</b> Spatial Data</a><ul>
<li class="chapter" data-level="1.1" data-path="spatial-data.html"><a href="spatial-data.html#introduction-to-landscape-genetics-workshop"><i class="fa fa-check"></i><b>1.1</b> Introduction to Landscape Genetics Workshop</a></li>
<li class="chapter" data-level="1.2" data-path="spatial-data.html"><a href="spatial-data.html#spatial-data-in-r"><i class="fa fa-check"></i><b>1.2</b> Spatial Data In R</a></li>
<li class="chapter" data-level="1.3" data-path="spatial-data.html"><a href="spatial-data.html#synopsis"><i class="fa fa-check"></i><b>1.3</b> Synopsis</a></li>
<li class="chapter" data-level="1.4" data-path="spatial-data.html"><a href="spatial-data.html#objectives"><i class="fa fa-check"></i><b>1.4</b> Objectives</a></li>
<li class="chapter" data-level="1.5" data-path="spatial-data.html"><a href="spatial-data.html#logistics-on-data"><i class="fa fa-check"></i><b>1.5</b> Logistics on Data</a></li>
<li class="chapter" data-level="1.6" data-path="spatial-data.html"><a href="spatial-data.html#projections"><i class="fa fa-check"></i><b>1.6</b> Projections</a><ul>
<li class="chapter" data-level="1.6.1" data-path="spatial-data.html"><a href="spatial-data.html#equatorial-projections"><i class="fa fa-check"></i><b>1.6.1</b> Equatorial Projections</a></li>
<li class="chapter" data-level="1.6.2" data-path="spatial-data.html"><a href="spatial-data.html#azimuth-projections"><i class="fa fa-check"></i><b>1.6.2</b> Azimuth Projections</a></li>
<li class="chapter" data-level="1.6.3" data-path="spatial-data.html"><a href="spatial-data.html#polar-conic-projections"><i class="fa fa-check"></i><b>1.6.3</b> Polar Conic Projections</a></li>
<li class="chapter" data-level="1.6.4" data-path="spatial-data.html"><a href="spatial-data.html#miscellaneous-projections"><i class="fa fa-check"></i><b>1.6.4</b> Miscellaneous Projections</a></li>
<li class="chapter" data-level="1.6.5" data-path="spatial-data.html"><a href="spatial-data.html#coordinate-systems"><i class="fa fa-check"></i><b>1.6.5</b> Coordinate Systems</a></li>
<li class="chapter" data-level="1.6.6" data-path="spatial-data.html"><a href="spatial-data.html#projection-summary"><i class="fa fa-check"></i><b>1.6.6</b> Projection Summary</a></li>
</ul></li>
<li class="chapter" data-level="1.7" data-path="spatial-data.html"><a href="spatial-data.html#the-sp-library"><i class="fa fa-check"></i><b>1.7</b> The <code>sp</code> Library</a><ul>
<li class="chapter" data-level="1.7.1" data-path="spatial-data.html"><a href="spatial-data.html#points"><i class="fa fa-check"></i><b>1.7.1</b> Points</a></li>
<li class="chapter" data-level="1.7.2" data-path="spatial-data.html"><a href="spatial-data.html#lines"><i class="fa fa-check"></i><b>1.7.2</b> Lines</a></li>
<li class="chapter" data-level="1.7.3" data-path="spatial-data.html"><a href="spatial-data.html#polygons"><i class="fa fa-check"></i><b>1.7.3</b> Polygons</a></li>
<li class="chapter" data-level="1.7.4" data-path="spatial-data.html"><a href="spatial-data.html#projecting-sp-objects."><i class="fa fa-check"></i><b>1.7.4</b> Projecting <code>sp</code> objects.</a></li>
<li class="chapter" data-level="1.7.5" data-path="spatial-data.html"><a href="spatial-data.html#points-lines-and-polygons-in-ggplot"><i class="fa fa-check"></i><b>1.7.5</b> Points, Lines, and Polygons in ggplot</a></li>
</ul></li>
<li class="chapter" data-level="1.8" data-path="spatial-data.html"><a href="spatial-data.html#rasters"><i class="fa fa-check"></i><b>1.8</b> Rasters</a></li>
<li class="chapter" data-level="1.9" data-path="spatial-data.html"><a href="spatial-data.html#modifying-rasters"><i class="fa fa-check"></i><b>1.9</b> Modifying Rasters</a><ul>
<li class="chapter" data-level="1.9.1" data-path="spatial-data.html"><a href="spatial-data.html#stacks-of-rasters"><i class="fa fa-check"></i><b>1.9.1</b> Stacks of Rasters</a></li>
</ul></li>
<li class="chapter" data-level="1.10" data-path="spatial-data.html"><a href="spatial-data.html#rasters-ggplot"><i class="fa fa-check"></i><b>1.10</b> Rasters &amp; ggplot</a></li>
<li class="chapter" data-level="1.11" data-path="spatial-data.html"><a href="spatial-data.html#d-visualization"><i class="fa fa-check"></i><b>1.11</b> 3D Visualization</a></li>
<li class="chapter" data-level="1.12" data-path="spatial-data.html"><a href="spatial-data.html#saving-exporting-vector-raster-objects"><i class="fa fa-check"></i><b>1.12</b> Saving &amp; Exporting Vector &amp; Raster Objects</a></li>
<li class="chapter" data-level="1.13" data-path="spatial-data.html"><a href="spatial-data.html#raster-manipulation"><i class="fa fa-check"></i><b>1.13</b> Raster Manipulation</a><ul>
<li class="chapter" data-level="1.13.1" data-path="spatial-data.html"><a href="spatial-data.html#cropping-rasters"><i class="fa fa-check"></i><b>1.13.1</b> Cropping Rasters</a></li>
<li class="chapter" data-level="1.13.2" data-path="spatial-data.html"><a href="spatial-data.html#cropping-rasters-via-polygons"><i class="fa fa-check"></i><b>1.13.2</b> Cropping Rasters Via Polygons</a></li>
<li class="chapter" data-level="1.13.3" data-path="spatial-data.html"><a href="spatial-data.html#cropping-rasters-via-convex-hull"><i class="fa fa-check"></i><b>1.13.3</b> Cropping Rasters Via Convex Hull</a></li>
<li class="chapter" data-level="1.13.4" data-path="spatial-data.html"><a href="spatial-data.html#extracting-point-data-from-rasters"><i class="fa fa-check"></i><b>1.13.4</b> Extracting Point Data From Rasters</a></li>
</ul></li>
<li class="chapter" data-level="1.14" data-path="spatial-data.html"><a href="spatial-data.html#s4-method-for-signature-raster"><i class="fa fa-check"></i><b>1.14</b> S4 method for signature ‘Raster’</a></li>
<li class="chapter" data-level="1.15" data-path="spatial-data.html"><a href="spatial-data.html#s4-method-for-signature-spatialgrid"><i class="fa fa-check"></i><b>1.15</b> S4 method for signature ‘SpatialGrid’</a></li>
<li class="chapter" data-level="1.16" data-path="spatial-data.html"><a href="spatial-data.html#s4-method-for-signature-spatialpolygons"><i class="fa fa-check"></i><b>1.16</b> S4 method for signature ‘SpatialPolygons’</a></li>
<li class="chapter" data-level="1.17" data-path="spatial-data.html"><a href="spatial-data.html#s4-method-for-signature-spatiallines"><i class="fa fa-check"></i><b>1.17</b> S4 method for signature ‘SpatialLines’</a></li>
<li class="chapter" data-level="1.18" data-path="spatial-data.html"><a href="spatial-data.html#s4-method-for-signature-spatialpoints"><i class="fa fa-check"></i><b>1.18</b> S4 method for signature ‘SpatialPoints’</a></li>
<li class="chapter" data-level="1.19" data-path="spatial-data.html"><a href="spatial-data.html#x-y-value"><i class="fa fa-check"></i><b>1.19</b> x y value</a></li>
<li class="chapter" data-level="1.20" data-path="spatial-data.html"><a href="spatial-data.html#section-4"><i class="fa fa-check"></i><b>1.20</b> 1 -113.3875 27.82083 116</a><ul>
<li class="chapter" data-level="1.20.1" data-path="spatial-data.html"><a href="spatial-data.html#extracting-neighborhood-data-from-rasters"><i class="fa fa-check"></i><b>1.20.1</b> Extracting Neighborhood Data from Rasters</a></li>
<li class="chapter" data-level="1.20.2" data-path="spatial-data.html"><a href="spatial-data.html#reprojecting-rasters"><i class="fa fa-check"></i><b>1.20.2</b> Reprojecting Rasters</a></li>
</ul></li>
<li class="chapter" data-level="1.21" data-path="spatial-data.html"><a href="spatial-data.html#questions"><i class="fa fa-check"></i><b>1.21</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="genetic-data.html"><a href="genetic-data.html"><i class="fa fa-check"></i><b>2</b> Genetic Data</a><ul>
<li class="chapter" data-level="2.1" data-path="genetic-data.html"><a href="genetic-data.html#synopsis-1"><i class="fa fa-check"></i><b>2.1</b> Synopsis</a></li>
<li class="chapter" data-level="2.2" data-path="genetic-data.html"><a href="genetic-data.html#objectives-1"><i class="fa fa-check"></i><b>2.2</b> Objectives</a></li>
<li class="chapter" data-level="2.3" data-path="genetic-data.html"><a href="genetic-data.html#genetic-markers-types-and-usage"><i class="fa fa-check"></i><b>2.3</b> Genetic Markers, Types and Usage</a><ul>
<li class="chapter" data-level="2.3.1" data-path="genetic-data.html"><a href="genetic-data.html#loading-external-data"><i class="fa fa-check"></i><b>2.3.1</b> Loading External Data</a></li>
<li class="chapter" data-level="2.3.2" data-path="genetic-data.html"><a href="genetic-data.html#built-in-data-sets"><i class="fa fa-check"></i><b>2.3.2</b> Built-In Data Sets</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="genetic-data.html"><a href="genetic-data.html#allele-frequencies"><i class="fa fa-check"></i><b>2.4</b> Allele Frequencies</a></li>
<li class="chapter" data-level="2.5" data-path="genetic-data.html"><a href="genetic-data.html#hardy-weinberg-equilibrium"><i class="fa fa-check"></i><b>2.5</b> Hardy-Weinberg Equilibrium</a><ul>
<li class="chapter" data-level="2.5.1" data-path="genetic-data.html"><a href="genetic-data.html#genetic-assumptions"><i class="fa fa-check"></i><b>2.5.1</b> Genetic Assumptions</a></li>
<li class="chapter" data-level="2.5.2" data-path="genetic-data.html"><a href="genetic-data.html#punnet-squares"><i class="fa fa-check"></i><b>2.5.2</b> Punnet Squares</a></li>
<li class="chapter" data-level="2.5.3" data-path="genetic-data.html"><a href="genetic-data.html#evolutionary-assumptions"><i class="fa fa-check"></i><b>2.5.3</b> Evolutionary Assumptions</a></li>
<li class="chapter" data-level="2.5.4" data-path="genetic-data.html"><a href="genetic-data.html#the-mechanics"><i class="fa fa-check"></i><b>2.5.4</b> The Mechanics</a></li>
<li class="chapter" data-level="2.5.5" data-path="genetic-data.html"><a href="genetic-data.html#trans-generational-transition-probabilities"><i class="fa fa-check"></i><b>2.5.5</b> Trans-Generational Transition Probabilities</a></li>
<li class="chapter" data-level="2.5.6" data-path="genetic-data.html"><a href="genetic-data.html#consequences-of-hwe"><i class="fa fa-check"></i><b>2.5.6</b> Consequences of HWE</a></li>
</ul></li>
<li class="chapter" data-level="2.6" data-path="genetic-data.html"><a href="genetic-data.html#genetic-diversity"><i class="fa fa-check"></i><b>2.6</b> Genetic Diversity</a><ul>
<li class="chapter" data-level="2.6.1" data-path="genetic-data.html"><a href="genetic-data.html#allelic-diversity"><i class="fa fa-check"></i><b>2.6.1</b> Allelic Diversity</a></li>
<li class="chapter" data-level="2.6.2" data-path="genetic-data.html"><a href="genetic-data.html#genotypic-diversity"><i class="fa fa-check"></i><b>2.6.2</b> Genotypic Diversity</a></li>
<li class="chapter" data-level="2.6.3" data-path="genetic-data.html"><a href="genetic-data.html#samples-from-several-locales"><i class="fa fa-check"></i><b>2.6.3</b> Samples from Several Locales</a></li>
<li class="chapter" data-level="2.6.4" data-path="genetic-data.html"><a href="genetic-data.html#multilocus-diversity"><i class="fa fa-check"></i><b>2.6.4</b> Multilocus Diversity</a></li>
<li class="chapter" data-level="2.6.5" data-path="genetic-data.html"><a href="genetic-data.html#inbreeding"><i class="fa fa-check"></i><b>2.6.5</b> Inbreeding</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="genetic-data.html"><a href="genetic-data.html#rarefaction"><i class="fa fa-check"></i><b>2.7</b> Rarefaction</a><ul>
<li class="chapter" data-level="2.7.1" data-path="genetic-data.html"><a href="genetic-data.html#mapping-diversity"><i class="fa fa-check"></i><b>2.7.1</b> Mapping Diversity</a></li>
</ul></li>
<li class="chapter" data-level="2.8" data-path="genetic-data.html"><a href="genetic-data.html#genetic-distance"><i class="fa fa-check"></i><b>2.8</b> Genetic Distance</a><ul>
<li class="chapter" data-level="2.8.1" data-path="genetic-data.html"><a href="genetic-data.html#individual-genetic-distance"><i class="fa fa-check"></i><b>2.8.1</b> Individual Genetic Distance</a></li>
<li class="chapter" data-level="2.8.2" data-path="genetic-data.html"><a href="genetic-data.html#population-level-genetic-distances"><i class="fa fa-check"></i><b>2.8.2</b> Population-Level Genetic Distances</a></li>
</ul></li>
<li class="chapter" data-level="2.9" data-path="genetic-data.html"><a href="genetic-data.html#genetic-structure"><i class="fa fa-check"></i><b>2.9</b> Genetic Structure</a></li>
<li class="chapter" data-level="2.10" data-path="genetic-data.html"><a href="genetic-data.html#f-statistics-and-thier-ilk"><i class="fa fa-check"></i><b>2.10</b> F-Statistics and Thier Ilk</a><ul>
<li class="chapter" data-level="2.10.1" data-path="genetic-data.html"><a href="genetic-data.html#issues-with-fixation-indices"><i class="fa fa-check"></i><b>2.10.1</b> Issues with Fixation Indices</a></li>
<li class="chapter" data-level="2.10.2" data-path="genetic-data.html"><a href="genetic-data.html#additional-x_st-like-parameters"><i class="fa fa-check"></i><b>2.10.2</b> Additional <span class="math inline">\(X_{ST}\)</span>-like Parameters</a></li>
</ul></li>
<li class="chapter" data-level="2.11" data-path="genetic-data.html"><a href="genetic-data.html#statistical-structure"><i class="fa fa-check"></i><b>2.11</b> Statistical Structure</a><ul>
<li class="chapter" data-level="2.11.1" data-path="genetic-data.html"><a href="genetic-data.html#final-thoughts-on-structure"><i class="fa fa-check"></i><b>2.11.1</b> Final Thoughts on Structure</a></li>
</ul></li>
<li class="chapter" data-level="2.12" data-path="genetic-data.html"><a href="genetic-data.html#questions-1"><i class="fa fa-check"></i><b>2.12</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="resistance-models.html"><a href="resistance-models.html"><i class="fa fa-check"></i><b>3</b> Resistance Models</a><ul>
<li class="chapter" data-level="3.1" data-path="resistance-models.html"><a href="resistance-models.html#synopsis-2"><i class="fa fa-check"></i><b>3.1</b> Synopsis</a></li>
<li class="chapter" data-level="3.2" data-path="resistance-models.html"><a href="resistance-models.html#objectives-2"><i class="fa fa-check"></i><b>3.2</b> Objectives</a></li>
<li class="chapter" data-level="3.3" data-path="resistance-models.html"><a href="resistance-models.html#resistance-costs"><i class="fa fa-check"></i><b>3.3</b> Resistance Costs</a><ul>
<li class="chapter" data-level="3.3.1" data-path="resistance-models.html"><a href="resistance-models.html#working-with-remotely-sensed-data"><i class="fa fa-check"></i><b>3.3.1</b> Working with Remotely Sensed Data</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="resistance-models.html"><a href="resistance-models.html#estimating-distances-on-resistance-rasters"><i class="fa fa-check"></i><b>3.4</b> Estimating Distances on Resistance Rasters</a><ul>
<li class="chapter" data-level="3.4.1" data-path="resistance-models.html"><a href="resistance-models.html#least-cost-distance"><i class="fa fa-check"></i><b>3.4.1</b> Least Cost Distance</a></li>
<li class="chapter" data-level="3.4.2" data-path="resistance-models.html"><a href="resistance-models.html#all-paths-circuitscape-distances"><i class="fa fa-check"></i><b>3.4.2</b> All Paths (CircuitScape) Distances</a></li>
<li class="chapter" data-level="3.4.3" data-path="resistance-models.html"><a href="resistance-models.html#logistical-issues"><i class="fa fa-check"></i><b>3.4.3</b> Logistical Issues</a></li>
<li class="chapter" data-level="3.4.4" data-path="resistance-models.html"><a href="resistance-models.html#pixel-size-and-path-lengths"><i class="fa fa-check"></i><b>3.4.4</b> Pixel Size and Path Lengths</a></li>
<li class="chapter" data-level="3.4.5" data-path="resistance-models.html"><a href="resistance-models.html#scaling-resistance"><i class="fa fa-check"></i><b>3.4.5</b> Scaling Resistance</a></li>
<li class="chapter" data-level="3.4.6" data-path="resistance-models.html"><a href="resistance-models.html#final-thoughts-on-raster-manipulations"><i class="fa fa-check"></i><b>3.4.6</b> Final Thoughts on Raster Manipulations</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="resistance-models.html"><a href="resistance-models.html#resistance-models-1"><i class="fa fa-check"></i><b>3.5</b> Resistance Models</a><ul>
<li class="chapter" data-level="3.5.1" data-path="resistance-models.html"><a href="resistance-models.html#the-mantel-test"><i class="fa fa-check"></i><b>3.5.1</b> The Mantel Test</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="resistance-models.html"><a href="resistance-models.html#is-vegetation-related-to-environment"><i class="fa fa-check"></i><b>3.6</b> Is vegetation related to environment?</a><ul>
<li class="chapter" data-level="3.6.1" data-path="resistance-models.html"><a href="resistance-models.html#the-partial-mantel"><i class="fa fa-check"></i><b>3.6.1</b> The Partial Mantel</a></li>
<li class="chapter" data-level="3.6.2" data-path="resistance-models.html"><a href="resistance-models.html#distance-regression"><i class="fa fa-check"></i><b>3.6.2</b> Distance Regression</a></li>
<li class="chapter" data-level="3.6.3" data-path="resistance-models.html"><a href="resistance-models.html#model-comparisons-concerns"><i class="fa fa-check"></i><b>3.6.3</b> Model Comparisons &amp; Concerns</a></li>
</ul></li>
<li class="chapter" data-level="3.7" data-path="resistance-models.html"><a href="resistance-models.html#questions-2"><i class="fa fa-check"></i><b>3.7</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="space-networks.html"><a href="space-networks.html"><i class="fa fa-check"></i><b>4</b> Space &amp; Networks</a><ul>
<li class="chapter" data-level="4.1" data-path="space-networks.html"><a href="space-networks.html#synopsis-3"><i class="fa fa-check"></i><b>4.1</b> Synopsis</a></li>
<li class="chapter" data-level="4.2" data-path="space-networks.html"><a href="space-networks.html#objectives-3"><i class="fa fa-check"></i><b>4.2</b> Objectives</a></li>
<li class="chapter" data-level="4.3" data-path="space-networks.html"><a href="space-networks.html#admixture"><i class="fa fa-check"></i><b>4.3</b> Admixture</a></li>
<li class="chapter" data-level="4.4" data-path="space-networks.html"><a href="space-networks.html#ordination"><i class="fa fa-check"></i><b>4.4</b> Ordination</a><ul>
<li class="chapter" data-level="4.4.1" data-path="space-networks.html"><a href="space-networks.html#principal-component-rotations"><i class="fa fa-check"></i><b>4.4.1</b> Principal Component Rotations</a></li>
<li class="chapter" data-level="4.4.2" data-path="space-networks.html"><a href="space-networks.html#hierarchical-clustering"><i class="fa fa-check"></i><b>4.4.2</b> Hierarchical Clustering</a></li>
<li class="chapter" data-level="4.4.3" data-path="space-networks.html"><a href="space-networks.html#interactive-tree-display"><i class="fa fa-check"></i><b>4.4.3</b> Interactive Tree Display</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="space-networks.html"><a href="space-networks.html#networks"><i class="fa fa-check"></i><b>4.5</b> Networks</a><ul>
<li class="chapter" data-level="4.5.1" data-path="space-networks.html"><a href="space-networks.html#node-edge-attributes"><i class="fa fa-check"></i><b>4.5.1</b> Node &amp; Edge Attributes</a></li>
<li class="chapter" data-level="4.5.2" data-path="space-networks.html"><a href="space-networks.html#plotting-a-graphs"><i class="fa fa-check"></i><b>4.5.2</b> Plotting a Graphs</a></li>
</ul></li>
<li class="chapter" data-level="4.6" data-path="space-networks.html"><a href="space-networks.html#not-run"><i class="fa fa-check"></i><b>4.6</b> Not run:</a></li>
<li class="chapter" data-level="4.7" data-path="space-networks.html"><a href="space-networks.html#endnot-run"><i class="fa fa-check"></i><b>4.7</b> End(Not run)</a></li>
<li class="chapter" data-level="4.8" data-path="space-networks.html"><a href="space-networks.html#mapping-networks"><i class="fa fa-check"></i><b>4.8</b> Mapping Networks</a></li>
<li class="chapter" data-level="4.9" data-path="space-networks.html"><a href="space-networks.html#genetic-distance-graphs"><i class="fa fa-check"></i><b>4.9</b> Genetic Distance Graphs</a></li>
<li class="chapter" data-level="4.10" data-path="space-networks.html"><a href="space-networks.html#population-graphs"><i class="fa fa-check"></i><b>4.10</b> Population Graphs</a></li>
<li class="chapter" data-level="4.11" data-path="space-networks.html"><a href="space-networks.html#adding-data-to-a-graph"><i class="fa fa-check"></i><b>4.11</b> Adding data to a graph</a><ul>
<li class="chapter" data-level="4.11.1" data-path="space-networks.html"><a href="space-networks.html#plotting-a-graph-using-ggplot2-routines"><i class="fa fa-check"></i><b>4.11.1</b> Plotting a graph using <strong>ggplot2</strong> routines</a></li>
<li class="chapter" data-level="4.11.2" data-path="space-networks.html"><a href="space-networks.html#reading-existing-popgraph-files"><i class="fa fa-check"></i><b>4.11.2</b> Reading Existing <strong>popgraph</strong> Files</a></li>
<li class="chapter" data-level="4.11.3" data-path="space-networks.html"><a href="space-networks.html#saving-population-graph-objects"><i class="fa fa-check"></i><b>4.11.3</b> Saving Population Graph Objects</a></li>
<li class="chapter" data-level="4.11.4" data-path="space-networks.html"><a href="space-networks.html#interactive-networks"><i class="fa fa-check"></i><b>4.11.4</b> Interactive Networks</a></li>
<li class="chapter" data-level="4.11.5" data-path="space-networks.html"><a href="space-networks.html#spatial-population-graphs"><i class="fa fa-check"></i><b>4.11.5</b> Spatial Population Graphs</a></li>
<li class="chapter" data-level="4.11.6" data-path="space-networks.html"><a href="space-networks.html#integrating-google-and-ggplot2-for-plotting"><i class="fa fa-check"></i><b>4.11.6</b> Integrating Google and <strong>ggplot2</strong> for Plotting</a></li>
<li class="chapter" data-level="4.11.7" data-path="space-networks.html"><a href="space-networks.html#integrating-raster-maps"><i class="fa fa-check"></i><b>4.11.7</b> Integrating Raster Maps</a></li>
<li class="chapter" data-level="4.11.8" data-path="space-networks.html"><a href="space-networks.html#extracting-spatial-data-using-population-graphs"><i class="fa fa-check"></i><b>4.11.8</b> Extracting Spatial Data Using Population Graphs</a></li>
</ul></li>
<li class="chapter" data-level="4.12" data-path="space-networks.html"><a href="space-networks.html#extracting-graph-theoretic-parameters"><i class="fa fa-check"></i><b>4.12</b> Extracting Graph-Theoretic Parameters</a><ul>
<li class="chapter" data-level="4.12.1" data-path="space-networks.html"><a href="space-networks.html#matrix-representations-of-population-graph-objects"><i class="fa fa-check"></i><b>4.12.1</b> Matrix Representations of Population Graph Objects</a></li>
<li class="chapter" data-level="4.12.2" data-path="space-networks.html"><a href="space-networks.html#edge-specific-parameters"><i class="fa fa-check"></i><b>4.12.2</b> Edge Specific Parameters</a></li>
</ul></li>
<li class="chapter" data-level="4.13" data-path="space-networks.html"><a href="space-networks.html#testing-for-topological-congruence"><i class="fa fa-check"></i><b>4.13</b> Testing for Topological Congruence</a></li>
<li class="chapter" data-level="4.14" data-path="space-networks.html"><a href="space-networks.html#questions-3"><i class="fa fa-check"></i><b>4.14</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="adaptive-landscape-genetics.html"><a href="adaptive-landscape-genetics.html"><i class="fa fa-check"></i><b>5</b> Adaptive Landscape Genetics</a><ul>
<li class="chapter" data-level="5.1" data-path="adaptive-landscape-genetics.html"><a href="adaptive-landscape-genetics.html#synopsis-4"><i class="fa fa-check"></i><b>5.1</b> Synopsis</a></li>
<li class="chapter" data-level="5.2" data-path="adaptive-landscape-genetics.html"><a href="adaptive-landscape-genetics.html#objectives-4"><i class="fa fa-check"></i><b>5.2</b> Objectives</a></li>
<li class="chapter" data-level="5.3" data-path="adaptive-landscape-genetics.html"><a href="adaptive-landscape-genetics.html#quantitative-genetics"><i class="fa fa-check"></i><b>5.3</b> Quantitative Genetics</a></li>
<li class="chapter" data-level="5.4" data-path="adaptive-landscape-genetics.html"><a href="adaptive-landscape-genetics.html#phenotypic-variance"><i class="fa fa-check"></i><b>5.4</b> Phenotypic Variance</a></li>
<li class="chapter" data-level="5.5" data-path="adaptive-landscape-genetics.html"><a href="adaptive-landscape-genetics.html#data-examples"><i class="fa fa-check"></i><b>5.5</b> Data Examples</a><ul>
<li class="chapter" data-level="5.5.1" data-path="adaptive-landscape-genetics.html"><a href="adaptive-landscape-genetics.html#measured-traits"><i class="fa fa-check"></i><b>5.5.1</b> Measured Traits</a></li>
</ul></li>
<li class="chapter" data-level="5.6" data-path="adaptive-landscape-genetics.html"><a href="adaptive-landscape-genetics.html#heritability"><i class="fa fa-check"></i><b>5.6</b> Heritability</a></li>
<li class="chapter" data-level="5.7" data-path="adaptive-landscape-genetics.html"><a href="adaptive-landscape-genetics.html#questions-4"><i class="fa fa-check"></i><b>5.7</b> Questions</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-r-environment.html"><a href="the-r-environment.html"><i class="fa fa-check"></i>The R Environment</a><ul>
<li class="chapter" data-level="" data-path="the-r-environment.html"><a href="the-r-environment.html#getting-r-configured"><i class="fa fa-check"></i>Getting R Configured</a><ul>
<li class="chapter" data-level="5.7.1" data-path="the-r-environment.html"><a href="the-r-environment.html#packages"><i class="fa fa-check"></i><b>5.7.1</b> Packages</a></li>
<li class="chapter" data-level="5.7.2" data-path="the-r-environment.html"><a href="the-r-environment.html#cran"><i class="fa fa-check"></i><b>5.7.2</b> CRAN</a></li>
<li class="chapter" data-level="5.7.3" data-path="the-r-environment.html"><a href="the-r-environment.html#github"><i class="fa fa-check"></i><b>5.7.3</b> GitHub</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-r-environment.html"><a href="the-r-environment.html#workshop-settings"><i class="fa fa-check"></i>Workshop Settings</a></li>
<li class="chapter" data-level="" data-path="the-r-environment.html"><a href="the-r-environment.html#troubleshooting"><i class="fa fa-check"></i>Troubleshooting</a><ul>
<li class="chapter" data-level="5.7.4" data-path="the-r-environment.html"><a href="the-r-environment.html#challenges-in-installation"><i class="fa fa-check"></i><b>5.7.4</b> Challenges in Installation</a></li>
<li class="chapter" data-level="5.7.5" data-path="the-r-environment.html"><a href="the-r-environment.html#rgdal-rgeos-issues"><i class="fa fa-check"></i><b>5.7.5</b> RGDAL &amp; RGEOS Issues</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-r-environment.html"><a href="the-r-environment.html#the-rstudio-environment"><i class="fa fa-check"></i>The RStudio Environment</a></li>
<li class="chapter" data-level="" data-path="the-r-environment.html"><a href="the-r-environment.html#data-types"><i class="fa fa-check"></i>Data Types</a><ul>
<li class="chapter" data-level="5.7.6" data-path="the-r-environment.html"><a href="the-r-environment.html#numeric-data-types"><i class="fa fa-check"></i><b>5.7.6</b> Numeric Data Types</a></li>
<li class="chapter" data-level="5.7.7" data-path="the-r-environment.html"><a href="the-r-environment.html#characters"><i class="fa fa-check"></i><b>5.7.7</b> Characters</a></li>
<li class="chapter" data-level="5.7.8" data-path="the-r-environment.html"><a href="the-r-environment.html#factors"><i class="fa fa-check"></i><b>5.7.8</b> Factors</a></li>
<li class="chapter" data-level="5.7.9" data-path="the-r-environment.html"><a href="the-r-environment.html#logical-types"><i class="fa fa-check"></i><b>5.7.9</b> Logical Types</a></li>
</ul></li>
<li class="chapter" data-level="" data-path="the-r-environment.html"><a href="the-r-environment.html#data-containers"><i class="fa fa-check"></i>Data Containers</a><ul>
<li class="chapter" data-level="5.7.10" data-path="the-r-environment.html"><a href="the-r-environment.html#vectors"><i class="fa fa-check"></i><b>5.7.10</b> Vectors</a></li>
<li class="chapter" data-level="5.7.11" data-path="the-r-environment.html"><a href="the-r-environment.html#matrices"><i class="fa fa-check"></i><b>5.7.11</b> Matrices</a></li>
<li class="chapter" data-level="5.7.12" data-path="the-r-environment.html"><a href="the-r-environment.html#lists"><i class="fa fa-check"></i><b>5.7.12</b> Lists</a></li>
<li class="chapter" data-level="5.7.13" data-path="the-r-environment.html"><a href="the-r-environment.html#data-frames"><i class="fa fa-check"></i><b>5.7.13</b> Data Frames</a></li>
</ul></li>
<li class="chapter" data-level="5.8" data-path="the-r-environment.html"><a href="the-r-environment.html#programming"><i class="fa fa-check"></i><b>5.8</b> Programming</a><ul>
<li class="chapter" data-level="5.8.1" data-path="the-r-environment.html"><a href="the-r-environment.html#function-writing"><i class="fa fa-check"></i><b>5.8.1</b> Function Writing</a></li>
<li class="chapter" data-level="5.8.2" data-path="the-r-environment.html"><a href="the-r-environment.html#variable-scope"><i class="fa fa-check"></i><b>5.8.2</b> Variable Scope</a></li>
<li class="chapter" data-level="5.8.3" data-path="the-r-environment.html"><a href="the-r-environment.html#decision-making"><i class="fa fa-check"></i><b>5.8.3</b> Decision Making</a></li>
<li class="chapter" data-level="5.8.4" data-path="the-r-environment.html"><a href="the-r-environment.html#flow-control"><i class="fa fa-check"></i><b>5.8.4</b> Flow Control</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references-cited.html"><a href="references-cited.html"><i class="fa fa-check"></i>References Cited</a></li>
<li class="divider"></li>
<li><a href="http://dyerlab.com" target="blank">the Dyer Laboratory</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Landscape Genetic Data Analysis</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="the-r-environment" class="section level1 unnumbered">
<h1>The R Environment</h1>
<div class="figure">
<img src="media/ch_farm.jpg" />

</div>
<blockquote>
<p>R is an open-source, community driven platform available for a wide variety of computer operating systems and is becoming a de facto standard in modern biological analyses. It is not a point-and-click interface, rather it is a rich analytical ecosystem that will make your research and scientific life more pleasurable.</p>
</blockquote>
<div id="getting-r-configured" class="section level2 unnumbered">
<h2>Getting R Configured</h2>
<p>The grammar of the R language was derived from another system called S-Plus. S-Plus was a proprietary analysis platform developed by AT&amp;T and licenses were sold for its use, mostly in industry and education. Given the closed nature of the S-Plus platform, R was developed with the goal of creating an interpreter that could read grammar similar to S-Plus but be available to the larger research community. The use of R has increased dramatically due to its open nature and the ability of people to share code solutions with relatively little barriers.</p>
<p>The main repository for R is located at the <a href="http://cran.r-project.org">CRAN Repository</a>, which is where you can download the latest version. It is in your best interests to make sure you update the underlying R system, changes are made continually (perhaps despite the outward appearance of the website).</p>
<p><img src="media/CRAN.png" width="385" /></p>
<p>The current version of this book uses version 3.2. To get the correct version, open the page and there should be a link at the top for your particular computing platform. Download the appropriate version and install it following the instructions appropriate for your computer.</p>
<div id="packages" class="section level3">
<h3><span class="header-section-number">5.7.1</span> Packages</h3>
<p>The base R system comes with enough functionality to get you going. By default, there is only a limited amount of functionality in R, which is a great thing. You only load and use the packages that you intend to use. There are just too many packages to have them all loaded into memory at all times and there is such a broad range of packages, it is not likely you’d need more than a small fraction of the packages during the course of all your analyses. Once you have a package, you can tell R that you intend to use it by either</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(package_name)</code></pre></div>
<p>or</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"> <span class="kw">library</span>(package_name)</code></pre></div>
<p>They are approximately equivalent, differing in only that the second one actually returns a TRUE or FALSE indicating the presence of that library on you machine. If you do not want to be mocked by other users of R, I would recommend the <code>library</code> version—there are situations where <code>require</code> will not do what you think you want it to do (even though it is a verb and should probably be the correct one to use grammatically).</p>
<p>There are, at present, a few different places you can get packages. The packages can either be downloaded from these online repositories and installed into R or you can install them from within R itself. Again, I’ll prefer the latter as it is a bit more straightforward.</p>
</div>
<div id="cran" class="section level3">
<h3><span class="header-section-number">5.7.2</span> CRAN</h3>
<p>The main repository for packages is hosted by the r-project page itself. There are packages with solutions to analyses ranging from Approximate Bayesian Computation to Zhang &amp; Pilon’s approaches to characterizing climatic trends. The list of these packages is large and ever growing. It can be found on CRAN under the packages menu. To install a package from this repository, you use the function</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;thePackageName&quot;</span>) </code></pre></div>
<p>You can see that R went to the CRAN mirror site (I use the rstudio one), downloaded the package, look for particular dependencies that that package may have and download them as well for you. It should install these packages for you and give you an affirmative message indicating it had done so.</p>
<p>At times, there are some packages that are not available in binary form for all computer systems (the rgdal package is one that comes to mind for which we will provide a work around later) and the packages need to be compiled. This means that you need to have some additional tools and/or libraries on your machine to take the code, compile it, and link it together to make the package. In these cases, the internet and the documentation that the developer provide are key to your sanity.</p>
</div>
<div id="github" class="section level3">
<h3><span class="header-section-number">5.7.3</span> GitHub</h3>
<p>There are an increasing number of projects that are being developed either in the open source community or shared among a set of developers. These projects are often hosted on <a href="http://www.github.com" class="uri">http://www.github.com</a> where you can get access to the latest code updates. The packages that I develop are hosted on Github at (<a href="http://github.com/dyerlab" class="uri">http://github.com/dyerlab</a>) and only pushed to CRAN when I make major changes.</p>
<p><img src="media/DyerlabGithub.png" width="498" /></p>
<p>To install packages from Github you need to install the devtools library from CRAN first</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;devtools&quot;</span>)
<span class="kw">library</span>(devtools)</code></pre></div>
<p>Then you need to use the devtools function <code>install_github()</code> to go grab it. To do so you need two separate pieces of information, the name of the developer who is creating the repository and the name of the repository it is contained within. For the gstudio package, the develop is <code>dyerlab</code> and the repository name is <code>gstudio</code>. If you are comfortable with git, you can also check out certain branches of development if you like with optional arguments to the <code>install_github()</code> function. Here is how you would install both the <code>gstudio</code> and <code>popgraph</code> libraries I use in this book.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install_github</span>(<span class="st">&quot;dyerlab/popgraph&quot;</span>)
<span class="kw">install_github</span>(<span class="st">&quot;dyerlab/gstudio&quot;</span>)</code></pre></div>
<p>If you are starting to work with R and intend to compile packages, there are some tools that you will need to have on your machine. For Windows machines, there is an rtools download EXE that you can get. On OSX, you need to download the developers tools from Apple (available on the Application Store for free). In either case, the developer (if they care about their code being used by others) should provide sufficient documentation. If you are working on Windows, I do not know how that system (and never have used it for any prolonged period of time) so you’ll have to look to the internet on where to find compilers and other developer tools.</p>
</div>
</div>
<div id="workshop-settings" class="section level2 unnumbered">
<h2>Workshop Settings</h2>
<p>This course was designed for people who already have some preliminary grasp of what R is and how to use it with a moderate amount of efficiency. In this section, I go over how to set up your computer to be able to tackle the tasks presented in this workshop. This will require you to install both R components as well as software from elsewhere. I have set up an automated script to do this for you and if you think this is <em>tl;dr</em>, just type:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">install.packages</span>(<span class="st">&quot;devtools&quot;</span>)
url &lt;-<span class="st"> &quot;https://raw.githubusercontent.com/dyerlab/Landscape-Genetics-Data-Analysis/master/library_loader.R&quot;</span>
devtools<span class="op">::</span><span class="kw">source_url</span>( url )</code></pre></div>
<p>If you have problems installing the <code>devtools</code> package and are on the Windows platform, you must go back to CRAN and download the Rtools set of utilities. It can be found at <a href="https://cran.r-project.org/bin/windows/Rtools/" class="uri">https://cran.r-project.org/bin/windows/Rtools/</a>. Install that and then go back and execute the code from above.</p>
<p>This file will download the</p>
</div>
<div id="troubleshooting" class="section level2 unnumbered">
<h2>Troubleshooting</h2>
<p>Some packages provide a unique set of problems for getting them onto your computer. There are a variety of reasons for this and Google is your friend (though it would be easier if R was named something more unique than the 18<sup><sup>th</sup></sup> letter of the alphabet…).</p>
<div id="challenges-in-installation" class="section level3">
<h3><span class="header-section-number">5.7.4</span> Challenges in Installation</h3>
<p>There are several challenges that you may face when configuring R for a workshop like this or when you upgrade your system and want to install all the packages you had on your old kit. Here are some things to consider if you run into issues.</p>
<ol style="list-style-type: decimal">
<li>On the Windows platform, you will most likely need to install the packages in a local repository. This means that <code>R</code> will create a folder in your home directory and put the packages in that folder. It has to do this because it needs to have write access to the folders and the normal place they are installed (for all the users on the machine) are only accessable by the administrator. You don’t want to run R (or RStudio) as administrator, this is would be bad (tm). So if the install asks, just say Yes I want to save a local copy for my libraries.</li>
<li>When packages are made, it is supposed to be required that the dependent packages are identified and easily installed. This mostly works, though there are times when it fails. When you run across errors on installation, the first thing you need to do is to try to figure out what the error is telling you. For some reason, many of the developers for <code>R</code> do not take the task of writing error messages with a lot of thought for the actual readers of the messages–they can be downright cryptic at times! That said, it is not uncommon to find that a particular dependency is not installed and must be configured properly prior to allowing you to finish your task. When this happens, just stop and go install that troublesome package and then go back to working on the suite of packages that need to be</li>
</ol>
</div>
<div id="rgdal-rgeos-issues" class="section level3">
<h3><span class="header-section-number">5.7.5</span> RGDAL &amp; RGEOS Issues</h3>
<p>Every time I upgrade R in any significant way, two libraries seem to raise their ugly heads and scream like a spoiled child—–<em>rgdal</em> and <em>rgeos</em>. Why do these two have to be SOOOO much of a pain? Why can’t we have a auto build of a binary with all the options in it for OSX? Who knows? I always feel like I get the fuzzy end of the lollipop with these two. Here is my latest approach for getting them going.</p>
<p>First you have to make sure you have the latest GDAL libraries. I used to get mine from <a href="http://www.kyngchaos.com/software/frameworks">Kyngchaos</a>, just download the framework, install it, and then do some kind of long R CMD INSTALL dance, which seems to no longer work for me. I also tried installing from Ripley’s repository and found that (a) It was a version older than the one I already had on my machine, and (b) you can’t install from that repository, there is a malformed header and the install.packages() function just barfs.</p>
<p>Time to try something new. I typically stay away from the various installer frameworks out there on OSX to keep everything in Frameworks. But this time, I used MacPorts. You can find the latest version here. Here is how I got it to help me out.</p>
<ul>
<li>Download XCode from Apple, it is both free and has a lot of tools that make your life as a programmer easier. It is a big package and you’ll have to install the command line developer tools as well. You will be prompted on how to do this.</li>
<li>Downloaded the version of macports for your OS, I’m currently on 10.11 and installed it with little problems. It takes a bit of time at the end of the installation because it is downloading a lot of information. Be patient.</li>
<li>In the terminal, I updated it <code>sudo ports -v selfupdate</code> and again be patient, it is going to grab a lot of stuff from the internet.</li>
<li>I then used it to install <code>gdal</code> as a unix library (rather than as a framework so it won’t be located in /Library/Frameworks) by sudo ports install <code>gdal</code>. There were a lot of dependencies for this one so it took a while.</li>
<li>I then had R install rgdal as <code>install.packages( rgdal, type=&quot;source&quot;)</code></li>
</ul>
<p>Worked like a charm.</p>
</div>
</div>
<div id="the-rstudio-environment" class="section level2 unnumbered">
<h2>The RStudio Environment</h2>
<p>By itself, R can be used in the terminal or as the basic interface the installer provides. While both of these methods are sufficient for working in R, they are less than optimal (IMHO). I believe one of the most important tools you can use is a good IDE as it helps you organize and work with your data in ways that focus more on the outcome and less on the implementation. I’ve spent a lot of time in both Emacs and Vim and while they may be tools for the geek elite, RStudio has made me much more productive in terms of output per unit time.</p>
<p><img src="media/RStudioIDE.png" width="632" /></p>
<p>The RStudio IDE can be can be downloaded directly from (<a href="http://rstudio.org" class="uri">http://rstudio.org</a>) and comes in varieties for desktops and servers. The packages are easy to install and contain all the instructions you need. If you run your own server, you can install it and do your analyses via a web interface that looks identical to the desktop client (in fact it is more similar than you perhaps know).</p>
<p>The interface has four panes, two of which (the source code editor and the terminal output) you will work with the most often. The other panes have information on the history of your project, plot output, packages, help, and a file browser. You can type in R commands in the terminal window and receive responses directly, just as normal. However, you can also type in your code into a script file (files ending in *.R) and run them directly. You can also create Markdown and LaTeX documents embedding your code in with the verbiage, which is evaluated any time you make a html, rtf, docx, or pdf output. All the code from R for this book was written in RMarkdown and parsed as an html document. If you are a serious user of R, you can use LaTeX or RMarkdown to make documents, slides, presentations, posters, etc. It is a versatile tool and one worth looking into, especially as it pertains to reproducible research (something we all need to strive for).</p>
</div>
<div id="data-types" class="section level2 unnumbered">
<h2>Data Types</h2>
<p>The very first hurdle you need to get over is the oddness in the way in which R assigns values to variables.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">variable &lt;-<span class="st"> </span>value</code></pre></div>
<p>Yes that is a less-than and dash character. This is the assignment operator that historically has been used and it is the one that I will stick with. In some cases you can use the ‘=’ to assign variables instead but then it takes away the R-ness of R itself. For decision making, the equality operator (e.g., is this equal to that) is the double equals sign ‘==’. We will get into that below where we talk about logical types and later in decision making.</p>
<p>If you are unaware of what type a particular variable may be, you can always use the <code>type()</code> function and R will tell you.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>( variable )</code></pre></div>
<p>R also has a pretty good help system built into itself. You can get help for any function by typing a question mark in front of the function name. This is a particularly awesome features because at the end of the help file, there is often examples of its usage, which are priceless. Here is the documentation for the ‘help’ function as given by:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">?help</code></pre></div>
<p>There are also package vignettes available (for most packages you download) that provide additional information on the routines, data sets, and other items included in these packages. You can get a list of vignettes currently installed on your machine by:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">vignette</span>()</code></pre></div>
<p>and vignettes for a particular package by passing the package name as an argument to the function itself.</p>
<div id="numeric-data-types" class="section level3">
<h3><span class="header-section-number">5.7.6</span> Numeric Data Types</h3>
<p>The quantitative measurements we make are often numeric, in that they can be represented as as a number with a decimal component (think weight, height, latitude, soil moisture, ear wax viscosity, etc.). The most basic type of data in R, is the numeric type and represents both integers and floating point numbers (n.b., there is a strict integer data type but it is often only needed when interfacing with other C libraries and can for what we are doing be disregarded).</p>
<p>Assigning a value to a variable is easy</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">3</span>
x</code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>By default, R automatically outputs whole numbers numbers within decimal values appropriately.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="dv">22</span><span class="op">/</span><span class="dv">7</span>
y</code></pre></div>
<pre><code>## [1] 3.142857</code></pre>
<p>If there is a mix of whole numbers and numbers with decimals together in a container such as</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">c</span>(x,y)</code></pre></div>
<pre><code>## [1] 3.000000 3.142857</code></pre>
<p>then both are shown with decimals. The <code>c()</code> part here is a function that combines several data objects together into a vector and is very useful. In fact, the use of vectors are are central to working in R and functions almost all the functions we use on individual variables can also be applied to vectors.</p>
<p>A word of caution should be made about numeric data types on any computer. Consider the following example.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span>.<span class="dv">3</span> <span class="op">/</span><span class="st"> </span><span class="dv">3</span>
x</code></pre></div>
<pre><code>## [1] 0.1</code></pre>
<p>which is exactly what we’d expect. However, the way in which computers store decimal numbers plays off our notion of significant digits pretty well. Look what happens when I print out x but carry out the number of decimal places.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">print</span>(x, <span class="dt">digits=</span><span class="dv">20</span>)</code></pre></div>
<pre><code>## [1] 0.099999999999999991673</code></pre>
<p>Not quite 0.1 is it? Not that far away from it but not exact. That is a general problem, not one that R has any more claim to than any other language and/or implementation. Does this matter much, probably not in the realm of the kinds of things we do in population genetics, it is just something that you should be aware of. You can make random sets of numeric data by using using functions describing various distributions. For example, some random numbers from the normal distribution are:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rnorm</span>(<span class="dv">10</span>)</code></pre></div>
<pre><code>##  [1]  0.2733268  1.5782763 -0.5160004 -1.3716224 -1.4366411  0.4811085
##  [7]  1.2092160 -1.9398876 -0.8316026  0.7021797</code></pre>
<p>from the normal distribution with designated mean and standard deviation:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rnorm</span>(<span class="dv">10</span>,<span class="dt">mean=</span><span class="dv">42</span>,<span class="dt">sd=</span><span class="dv">12</span>)</code></pre></div>
<pre><code>##  [1] 46.12683 48.50483 54.01920 31.73384 35.81057 56.59950 37.23531
##  [8] 51.05522 39.65403 44.99526</code></pre>
<p>A poisson distribution with mean 2:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rpois</span>(<span class="dv">10</span>,<span class="dt">lambda =</span> <span class="dv">2</span>)</code></pre></div>
<pre><code>##  [1] 0 1 3 4 4 2 2 3 4 3</code></pre>
<p>and the <span class="math inline">\(\chi^2\)</span> distribution with 1 degree of freedom:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rchisq</span>(<span class="dv">10</span>, <span class="dt">df=</span><span class="dv">1</span>)</code></pre></div>
<pre><code>##  [1] 2.244461e+00 5.427283e-01 1.116825e-01 4.112455e-03 4.307145e+00
##  [6] 2.387042e+00 3.037029e-02 2.714920e+00 1.932513e+00 1.698449e-05</code></pre>
<p>There are several more distributions that if you need to access random numbers, quantiles, probability densities, and cumulative density values are available.</p>
<div id="coercion-to-numeric" class="section level4">
<h4><span class="header-section-number">5.7.6.1</span> Coercion to Numeric</h4>
<p>All data types have the potential ability to take another variable and coerce it into their type. Some combinations make sense, and some do not. For example, if you load in a CSV data file using read_csv(), and at some point a stray non-numeric character was inserted into one of the cells on your spreadsheet, R will interpret the entire column as a character type rather than as a numeric type. This can be a very frustrating thing, spreadsheets should generally be considered evil as they do all kinds of stuff behind the scenes and make your life less awesome.</p>
<p>Here is an example of coercion of some data that is initially defined as a set of characters</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;42&quot;</span>,<span class="st">&quot;99&quot;</span>)
x</code></pre></div>
<pre><code>## [1] &quot;42&quot; &quot;99&quot;</code></pre>
<p>and is coerced into a numeric type using the as.numeric() function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">as.numeric</span>( x )
y</code></pre></div>
<pre><code>## [1] 42 99</code></pre>
<p>It is a built-in feature of the data types in R that they all have (or should have if someone is producing a new data type and is being courteous to their users) an <code>as.X()</code> function. This is where the data type decides if the values asked to be coerced are reasonable or if you need to be reminded that what you are asking is not possible. Here is an example where I try to coerce a non-numeric variable into a number.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> &quot;The night is dark and full of terrors...&quot;</span>
<span class="kw">as.numeric</span>( x )</code></pre></div>
<pre><code>## Warning: NAs introduced by coercion</code></pre>
<pre><code>## [1] NA</code></pre>
<p>By default, the result should be NA (missing data/non-applicable) if you ask for things that are not possible.</p>
</div>
</div>
<div id="characters" class="section level3">
<h3><span class="header-section-number">5.7.7</span> Characters</h3>
<p>A collection of letters, number, and or punctuation is represented as a character data type. These are enclosed in either single or double quotes and are considered a single entity. For example, my name can be represented as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">prof &lt;-<span class="st"> &quot;Rodney J. Dyer&quot;</span>
prof</code></pre></div>
<pre><code>## [1] &quot;Rodney J. Dyer&quot;</code></pre>
<p>In R, character variables are considered to be a single entity, that is the entire prof variable is a single unit, not a collection of characters. This is in part due to the way in which vectors of variables are constructed in the language. For example, if you are looking at the length of the variable I assigned my name to you see</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(prof)</code></pre></div>
<pre><code>## [1] 1</code></pre>
<p>which shows that there is only one ‘character’ variable. If, as is often the case, you are interested in knowing how many characters are in the variable prof, then you use the</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">nchar</span>(prof)</code></pre></div>
<pre><code>## [1] 14</code></pre>
<p>function instead. This returns the number of characters (even the non-printing ones like tabs and spaces.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">nchar</span>(<span class="st">&quot; </span><span class="ch">\t</span><span class="st"> &quot;</span>)</code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>As all other data types, you can define a vector of character values using the <code>c()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> &quot;I am&quot;</span>
y &lt;-<span class="st"> &quot;not&quot;</span>
z &lt;-<span class="st"> &#39;a looser&#39;</span>
terms &lt;-<span class="st"> </span><span class="kw">c</span>(x,y,z)
terms</code></pre></div>
<pre><code>## [1] &quot;I am&quot;     &quot;not&quot;      &quot;a looser&quot;</code></pre>
<p>And looking at the <code>length()</code> and <code>nchar()</code> of this you can see how these operations differ.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(terms)</code></pre></div>
<pre><code>## [1] 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">nchar</span>(terms)</code></pre></div>
<pre><code>## [1] 4 3 8</code></pre>
<div id="concatenation-of-characters" class="section level4">
<h4><span class="header-section-number">5.7.7.1</span> Concatenation of Characters</h4>
<p>Another common use of characters is concatenating them into single sequences. Here we use the function <code>paste()</code> and can set the separators (or characters that are inserted between entities when we collapse vectors). Here is an example, entirely fictional and only provided for instructional purposes only.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">paste</span>(terms, <span class="dt">collapse=</span><span class="st">&quot; &quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;I am not a looser&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">paste</span>(x,z)</code></pre></div>
<pre><code>## [1] &quot;I am a looser&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">paste</span>(x,z,<span class="dt">sep=</span><span class="st">&quot; not &quot;</span>)</code></pre></div>
<pre><code>## [1] &quot;I am not a looser&quot;</code></pre>
</div>
<div id="coercion-to-characters" class="section level4">
<h4><span class="header-section-number">5.7.7.2</span> Coercion to Characters</h4>
<p>A character data type is often the most basal type of data you can work with. For example, consider the case where you have named sample locations. These can be kept as a character data type or as a factor (see below). There are benefits and drawbacks to each representation of the same data (see below). By default (as of the version of R I am currently using when writing this book), if you use a function like read_table() to load in an external file, columns of character data will be treated as factors. This can be good behavior if all you are doing is loading in data and running an analysis, or it can be a total pain in the backside if you are doing more manipulative analyses.</p>
<p>Here is an example of coercing a numeric type into a character type using the <code>as.character()</code> function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">42</span>
x</code></pre></div>
<pre><code>## [1] 42</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">as.character</span>(x)
y</code></pre></div>
<pre><code>## [1] &quot;42&quot;</code></pre>
</div>
</div>
<div id="factors" class="section level3">
<h3><span class="header-section-number">5.7.8</span> Factors</h3>
<p>A factor is a categorical data type. If you are coming from SAS, these are class variables. If you are not, then perhaps you can think of them as mutually exclusive classifications. For example, an sample may be assigned to one particular locale, one particular region, and one particular species. Across all the data you may have several species, regions, and locales. These are finite, and defined, sets of categories. One of the more common headaches encountered by people new to R is working with factor types and trying to add categories that are not already defined.</p>
<p>Since factors are categorical, it is in your best interest to make sure you label them in as descriptive as a fashion as possible. You are not saving space or cutting down on computational time to take shortcuts and label the locale for Rancho Santa Maria as RSN or pop3d or 5. Our computers are fast and large enough, and our programmers are cleaver enough, to not have to rename our populations in numeric format to make them work (hello STRUCTURE I’m calling you out here). The only thing you have to loose by adopting a reasonable naming scheme is confusion in your output.</p>
<p>To define a factor type, you use the function <code>factor()</code> and pass it a vector of values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">region &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;North&quot;</span>,<span class="st">&quot;North&quot;</span>,<span class="st">&quot;South&quot;</span>,<span class="st">&quot;East&quot;</span>,<span class="st">&quot;East&quot;</span>,<span class="st">&quot;South&quot;</span>,<span class="st">&quot;West&quot;</span>,<span class="st">&quot;West&quot;</span>,<span class="st">&quot;West&quot;</span>)
region &lt;-<span class="st"> </span><span class="kw">factor</span>( region )
region</code></pre></div>
<pre><code>## [1] North North South East  East  South West  West  West 
## Levels: East North South West</code></pre>
<p>When you print out the values, it shows you all the levels present for the factor. If you have levels that are not present in your data set, when you define it, you can tell R to consider additional levels of this factor by passing the optional levels= argument as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">region &lt;-<span class="st"> </span><span class="kw">factor</span>( region, <span class="dt">levels=</span><span class="kw">c</span>(<span class="st">&quot;North&quot;</span>,<span class="st">&quot;South&quot;</span>,<span class="st">&quot;East&quot;</span>,<span class="st">&quot;West&quot;</span>,<span class="st">&quot;Central&quot;</span>))
region</code></pre></div>
<pre><code>## [1] North North South East  East  South West  West  West 
## Levels: North South East West Central</code></pre>
<p>If you try to add a data point to a factor list that does not have the factor that you are adding, it will give you an error (or ‘barf’ as I like to say).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">region[<span class="dv">1</span>] &lt;-<span class="st"> &quot;Bob&quot;</span></code></pre></div>
<pre><code>## Warning in `[&lt;-.factor`(`*tmp*`, 1, value = &quot;Bob&quot;): invalid factor level,
## NA generated</code></pre>
<p>Now, I have to admit that the Error message in its entirety, with its <code>“[&lt;-.factor</code>(<code>*tmp*</code>, 1, value = “Bob”)“` part is, perhaps, not the most informative. Agreed. However, the “invalid factor level” does tell you something useful. Unfortunately, the programmers that put in the error handling system in R did not quite adhere to the spirit of the “fail loudly” mantra. It is something you will have to get good at. Google is your friend, and if you post a questions to (<a href="http://stackoverflow.org" class="uri">http://stackoverflow.org</a>) or the R user list without doing serious homework, put on your asbestos shorts!</p>
<p>Unfortunately, the error above changed the first element of the region vector to NA (missing data). I’ll turn it back before we move too much further.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">region[<span class="dv">1</span>] &lt;-<span class="st"> &quot;North&quot;</span></code></pre></div>
<p>Factors in R can be either unordered (as say locale may be since locale A is not <code>&gt;</code>, <code>=</code>, or <code>&lt;</code> locale B) or they may be ordered categories as in <code>Small &lt; Medium &lt; Large &lt; X-Large</code>. When you create the factor, you need to indicate if it is an ordered type (by default it is not). If the factors are ordered in some way, you can also create an ordination on the data. If you do not pass a levels= option to the <code>factors()</code> function, it will take the order in which they occur in data you pass to it. If you want to specify an order for the factors specifically, pass the optional <code>levels=</code> and they will be ordinated in the order given there.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">region &lt;-<span class="st"> </span><span class="kw">factor</span>( region, <span class="dt">ordered=</span><span class="ot">TRUE</span>, <span class="dt">levels =</span> <span class="kw">c</span>(<span class="st">&quot;West&quot;</span>, <span class="st">&quot;North&quot;</span>, <span class="st">&quot;South&quot;</span>, <span class="st">&quot;East&quot;</span>) )
region</code></pre></div>
<pre><code>## [1] North North South East  East  South West  West  West 
## Levels: West &lt; North &lt; South &lt; East</code></pre>
<div id="missing-levels-in-factors" class="section level4">
<h4><span class="header-section-number">5.7.8.1</span> Missing Levels in Factors</h4>
<p>There are times when you have a subset of data that do not have all the potential categories.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">subregion &lt;-<span class="st"> </span>region[ <span class="dv">3</span><span class="op">:</span><span class="dv">9</span> ]
subregion</code></pre></div>
<pre><code>## [1] South East  East  South West  West  West 
## Levels: West &lt; North &lt; South &lt; East</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">table</span>( subregion )</code></pre></div>
<pre><code>## subregion
##  West North South  East 
##     3     0     2     2</code></pre>
</div>
</div>
<div id="logical-types" class="section level3">
<h3><span class="header-section-number">5.7.9</span> Logical Types</h3>
<p>A logical type is either TRUE or FALSE, there is no in-between. It is common to use these types in making decisions (see if-else decisions) to check a specific condition being satisfied. To define logical variables you can either use the TRUE or FALSE directly</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">canThrow &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">FALSE</span>, <span class="ot">TRUE</span>, <span class="ot">FALSE</span>, <span class="ot">FALSE</span>, <span class="ot">FALSE</span>)
canThrow</code></pre></div>
<pre><code>## [1] FALSE  TRUE FALSE FALSE FALSE</code></pre>
<p>or can implement some logical condition</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">stable &lt;-<span class="st"> </span><span class="kw">c</span>( <span class="st">&quot;RGIII&quot;</span> <span class="op">==</span><span class="st"> </span><span class="dv">0</span>, <span class="kw">nchar</span>(<span class="st">&quot;Marshawn&quot;</span>) <span class="op">==</span><span class="st"> </span><span class="dv">8</span>)
stable</code></pre></div>
<pre><code>## [1] FALSE  TRUE</code></pre>
<p>on the variables. Notice here how each of the items is actually evaluated as to determine the truth of each expression. In the first case, the character is not equal to zero and in the second, the number of characters (what <code>nchar()</code> does) is indeed equal to 8 for the character string “Marshawn”.</p>
<p>It is common to use logical types to serve as indices for vectors. Say for example, you have a vector of data that you want to select some subset from.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">data &lt;-<span class="st"> </span><span class="kw">rnorm</span>(<span class="dv">20</span>)
data</code></pre></div>
<pre><code>##  [1]  1.18517495  0.46125954 -0.06466614 -1.66814109  0.33866849
##  [6] -1.41402694 -0.28646127 -0.03298617  0.29089122 -0.75672944
## [11] -0.33314933  0.96239408 -0.95843425  0.84305530  0.66450974
## [16] -0.47194843  0.58267724  1.64476054 -0.32741211  0.32437548</code></pre>
<p>Perhaps you are on interested in the non-negative values</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">data[ data <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span> ]</code></pre></div>
<pre><code>##  [1] 1.1851750 0.4612595 0.3386685 0.2908912 0.9623941 0.8430553 0.6645097
##  [8] 0.5826772 1.6447605 0.3243755</code></pre>
<p>If you look at the condition being passed to as the index</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">data <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span></code></pre></div>
<pre><code>##  [1]  TRUE  TRUE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE
## [12]  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE</code></pre>
<p>you see that individually, each value in the data vector is being evaluated as a logical value, satisfying the condition that it is strictly greater than zero. When you pass that as indices to a vector it only shows the indices that are <code>TRUE</code>.</p>
<p>You can coerce a value into a logical if you understand the rules. Numeric types that equal 0 (zero) are <code>FALSE</code>, always. Any non-zero value is considered <code>TRUE</code>. Here I use the modulus operator, <code>%%</code>, which provides the remainder of a division.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="dv">1</span><span class="op">:</span><span class="dv">20</span> <span class="op">%%</span><span class="st"> </span><span class="dv">2</span></code></pre></div>
<pre><code>##  [1] 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0 1 0</code></pre>
<p>which used as indices give us</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">data[ (<span class="dv">1</span><span class="op">:</span><span class="dv">20</span> <span class="op">%%</span><span class="st"> </span><span class="dv">2</span>) <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span> ]</code></pre></div>
<pre><code>##  [1]  1.18517495 -0.06466614  0.33866849 -0.28646127  0.29089122
##  [6] -0.33314933 -0.95843425  0.66450974  0.58267724 -0.32741211</code></pre>
<p>You can get as complicated in the creation of indices as you like, even using logical operators such as OR and AND. I leave that as an example for you to play with.</p>
</div>
</div>
<div id="data-containers" class="section level2 unnumbered">
<h2>Data Containers</h2>
<p>We almost never work with a single datum<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a>, rather we keep lots of data. Moreover, the kinds of data are often heterogeneous, including categorical (Populations, Regions), continuous (coordinates, rainfall, elevation), imagry (hyperspectral, LiDAR), and perhaps even genetic. R has a very rich set of containers into which we can stuff our data as we work with it. Here these container types are examined and the restrictions and benefits associated with each type are explained.</p>
<div id="vectors" class="section level3">
<h3><span class="header-section-number">5.7.10</span> Vectors</h3>
<p>We have already seen several examples of several vectors in action (see the introduction to Numeric data types for example). A vector of objects is simply a collection of them, often created using the <code>c()</code> function (<em>c</em> for combine). Vectorized data is restricted to having homogeneous data types—you cannot mix character and numeric types in the same vector. If you try to mix types, R will either coerce your data into a reasonable type</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>)
x</code></pre></div>
<pre><code>## [1] 1 2 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">TRUE</span>,<span class="ot">FALSE</span>)
y</code></pre></div>
<pre><code>## [1]  TRUE  TRUE FALSE</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;I&quot;</span>,<span class="st">&quot;am&quot;</span>,<span class="st">&quot;not&quot;</span>,<span class="st">&quot;a&quot;</span>,<span class="st">&quot;looser&quot;</span>)
z</code></pre></div>
<pre><code>## [1] &quot;I&quot;      &quot;am&quot;     &quot;not&quot;    &quot;a&quot;      &quot;looser&quot;</code></pre>
<p>or coearce them into one type that is amenable to all the types of data that you have given it. In this example, a Logical, Character, Constant, and Function are combined resulting in a vector output of type Character.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">w &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">TRUE</span>, <span class="st">&quot;1&quot;</span>, pi, <span class="kw">ls</span>())
w</code></pre></div>
<pre><code>##  [1] &quot;TRUE&quot;             &quot;1&quot;                &quot;3.14159265358979&quot;
##  [4] &quot;canThrow&quot;         &quot;data&quot;             &quot;prof&quot;            
##  [7] &quot;region&quot;           &quot;stable&quot;           &quot;subregion&quot;       
## [10] &quot;terms&quot;            &quot;x&quot;                &quot;y&quot;               
## [13] &quot;z&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">class</span>(w)</code></pre></div>
<pre><code>## [1] &quot;character&quot;</code></pre>
<p>Accessing elements within a vector are done using the square bracket <code>[]</code> notation. All indices (for vectors and matrices) start at 1 (not zero as is the case for some languages). Getting and setting the components within a vector are accomplished using numeric indices with the assignment operators just like we do for variables containing a single value.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x</code></pre></div>
<pre><code>## [1] 1 2 3</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[<span class="dv">1</span>] &lt;-<span class="st"> </span><span class="dv">2</span>
x[<span class="dv">3</span>] &lt;-<span class="st"> </span><span class="dv">1</span>
x</code></pre></div>
<pre><code>## [1] 2 2 1</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x[<span class="dv">2</span>]</code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>A common type of vector is that of a sequences. We use sequences all the time, to iterate through a list, to counting generations, etc. There are a few ways to generate sequences, depending upon the step sequence. For a sequence of whole numbers, the easiest is through the use of the colon operator.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">6</span>
x</code></pre></div>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<p>This provides a nice shorthand for getting the values X:Y from X to Y, inclusive. It is also possible to go backwards using this operator, counting down from X to Y as in:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">5</span><span class="op">:</span><span class="dv">2</span>
x</code></pre></div>
<pre><code>## [1] 5 4 3 2</code></pre>
<p>The only constraint here is that we are limited to a step size of 1.0. It is possible to use non-integers as the bounds, it will just count up by 1.0 each time.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="fl">3.2</span><span class="op">:</span><span class="fl">8.4</span>
x</code></pre></div>
<pre><code>## [1] 3.2 4.2 5.2 6.2 7.2 8.2</code></pre>
<p>If you are interested in making a sequence with a step other than 1.0, you can use the <code>seq()</code> function. If you do not provide a step value, it defaults to 1.0.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">6</span>)
y</code></pre></div>
<pre><code>## [1] 1 2 3 4 5 6</code></pre>
<p>But if you do, it will use that instead.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">z &lt;-<span class="st"> </span><span class="kw">seq</span>(<span class="dv">1</span>,<span class="dv">20</span>,<span class="dt">by=</span><span class="dv">2</span>)
z</code></pre></div>
<pre><code>##  [1]  1  3  5  7  9 11 13 15 17 19</code></pre>
<p>It is also possible to create a vector of objects as repetitions using the <code>rep()</code> (for repeat) function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rep</span>(<span class="st">&quot;Beetlejuice&quot;</span>,<span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] &quot;Beetlejuice&quot; &quot;Beetlejuice&quot; &quot;Beetlejuice&quot;</code></pre>
<p>If you pass a vector of items to <code>rep()</code>, it can repeat these as either a vector being repeated (the default value)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="st">&quot;No&quot;</span>,<span class="st">&quot;Free&quot;</span>,<span class="st">&quot;Lunch&quot;</span>)
<span class="kw">rep</span>(x,<span class="dt">time=</span><span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] &quot;No&quot;    &quot;Free&quot;  &quot;Lunch&quot; &quot;No&quot;    &quot;Free&quot;  &quot;Lunch&quot; &quot;No&quot;    &quot;Free&quot;  &quot;Lunch&quot;</code></pre>
<p>or as each item in the vector repeated.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">rep</span>(x,<span class="dt">each=</span><span class="dv">3</span>)</code></pre></div>
<pre><code>## [1] &quot;No&quot;    &quot;No&quot;    &quot;No&quot;    &quot;Free&quot;  &quot;Free&quot;  &quot;Free&quot;  &quot;Lunch&quot; &quot;Lunch&quot; &quot;Lunch&quot;</code></pre>
</div>
<div id="matrices" class="section level3">
<h3><span class="header-section-number">5.7.11</span> Matrices</h3>
<p>A matrix is a 2- or higher dimensional container, most commonly used to store numeric data types. There are some libraries that use matrices in more than two dimensions (rows and columns and sheets), though you will not run across them too often. Here I restrict myself to only 2-dimensional matrices.</p>
<p>You can define a matrix by giving it a set of values and an indication of the number of rows and columns you want. The easiest matrix to try is one with empty values:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">matrix</span>(<span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">ncol=</span><span class="dv">2</span>)</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]   NA   NA
## [2,]   NA   NA</code></pre>
<p>Perhaps more useful is one that is pre-populated with values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="dt">nrow=</span><span class="dv">2</span> )</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    3
## [2,]    2    4</code></pre>
<p>Notice that here, there were four entries and I only specified the number of rows required. By default the ‘filling-in’ of the matrix will proceed down column (<em>by-column</em>). In this example, we have the first column with the first two entries and the last two entries down the second column. If you want it to fill by row, you can pass the optional argument</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">matrix</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">4</span>, <span class="dt">nrow=</span><span class="dv">2</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    2
## [2,]    3    4</code></pre>
<p>and it will fill <em>by-row</em>.</p>
<p>When filling matrices, the default size and the size of the data being added to the matrix are critical. For example, I can create a matrix as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">Y &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),<span class="dt">ncol=</span><span class="dv">2</span>,<span class="dt">byrow=</span><span class="ot">TRUE</span>)
Y</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    1    2
## [2,]    3    4
## [3,]    5    6</code></pre>
<p>or</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),<span class="dt">nrow=</span><span class="dv">2</span>)
X</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    3    5
## [2,]    2    4    6</code></pre>
<p>and both produce a similar matrix, only transposed.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X <span class="op">==</span><span class="st"> </span><span class="kw">t</span>(Y)</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,] TRUE TRUE TRUE
## [2,] TRUE TRUE TRUE</code></pre>
<p>In the example above, the number of rows (or columns) was a clean multiple of the number of entries. However, if it is not, R will fill in values.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X &lt;-<span class="st"> </span><span class="kw">matrix</span>(<span class="kw">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>),<span class="dt">ncol=</span><span class="dv">4</span>, <span class="dt">byrow=</span><span class="ot">TRUE</span>)</code></pre></div>
<pre><code>## Warning in matrix(c(1, 2, 3, 4, 5, 6), ncol = 4, byrow = TRUE): data length
## [6] is not a sub-multiple or multiple of the number of columns [4]</code></pre>
<p>Notice how you get a warning from the interpreter. But that does not stop it from filling in the remaining slots by starting over in the sequence of numbers you passed to it.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X</code></pre></div>
<pre><code>##      [,1] [,2] [,3] [,4]
## [1,]    1    2    3    4
## [2,]    5    6    1    2</code></pre>
<p>The dimensionality of a matrix (and <code>data.frame</code> as we will see shortly) is returned by the <code>dim()</code> function. This will provide the number of rows and columns as a vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">dim</span>(X)</code></pre></div>
<pre><code>## [1] 2 4</code></pre>
<p>Accessing elements to retrieve or set their values within a matrix is done using the square brackets just like for a vector but you need to give <code>[row,col]</code> indices. Again, these are 1-based so that</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X[<span class="dv">1</span>,<span class="dv">3</span>]</code></pre></div>
<pre><code>## [1] 3</code></pre>
<p>is the entry in the 1st row and 3rd column.</p>
<p>You can also use ‘slices’ through a matrix to get the rows</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X[<span class="dv">1</span>,]</code></pre></div>
<pre><code>## [1] 1 2 3 4</code></pre>
<p>or columns</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X[,<span class="dv">3</span>]</code></pre></div>
<pre><code>## [1] 3 1</code></pre>
<p>of data. Here you just omit the index for the entity you want to span. Notice that when you grab a slice, even if it is a column, is given as a vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">length</span>(X[,<span class="dv">3</span>])</code></pre></div>
<pre><code>## [1] 2</code></pre>
<p>You can grab a sub-matrix using slices if you give a range (or sequence) of indices.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X[,<span class="dv">2</span><span class="op">:</span><span class="dv">3</span>]</code></pre></div>
<pre><code>##      [,1] [,2]
## [1,]    2    3
## [2,]    6    1</code></pre>
<p>If you ask for values from a matrix that exceed its dimensions, R will give you an error.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">X[<span class="dv">1</span>,<span class="dv">8</span>]</code></pre></div>
<pre><code>## Error in X[1, 8] : subscript out of bounds
## Calls: &lt;Anonymous&gt; ... handle -&gt; withCallingHandlers -&gt; withVisible -&gt; eval -&gt; eval
## Execution halted</code></pre>
<p>There are a few cool extensions of the <code>rep()</code> function that can be used to create matrices as well. They are optional values that can be passed to the function.</p>
<ul>
<li><code>times=x</code>: This is the default option that was occupied by the ‘3’ in the example above and represents the number of times that first argument will be repeated.<br />
</li>
<li><code>each=x</code> This will take each element in the first argument are repeat them <code>each</code> times.<br />
</li>
<li><code>length.out=x</code>: This make the result equal in length to <code>x</code>.</li>
</ul>
<p>In combination, these can be quite helpful. Here is an example using numeric sequences in which it is necessary to find the index of all entries in a 3x2 matrix. To make the indices, I bind two columns together using <code>cbind()</code>. There is a matching row binding function, denoted as <code>rbind()</code> (perhaps not so surprisingly). What is returned is a matrix</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">indices &lt;-<span class="st"> </span><span class="kw">cbind</span>( <span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">2</span>, <span class="dt">each=</span><span class="dv">3</span>), <span class="kw">rep</span>(<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>,<span class="dt">times=</span><span class="dv">2</span>), <span class="kw">rep</span>(<span class="dv">5</span>,<span class="dt">length.out=</span><span class="dv">6</span>)  )
indices</code></pre></div>
<pre><code>##      [,1] [,2] [,3]
## [1,]    1    1    5
## [2,]    1    2    5
## [3,]    1    3    5
## [4,]    2    1    5
## [5,]    2    2    5
## [6,]    2    3    5</code></pre>
</div>
<div id="lists" class="section level3">
<h3><span class="header-section-number">5.7.12</span> Lists</h3>
<p>A list is a type of vector but is indexed by ‘keys’ rather than by numeric indices. Moreover, lists can contain heterogeneous types of data (e.g., values of different <code>class</code>), which is not possible in a vector type. For example, consider the list</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">theList &lt;-<span class="st"> </span><span class="kw">list</span>( <span class="dt">x=</span><span class="kw">seq</span>(<span class="dv">2</span>,<span class="dv">40</span>, <span class="dt">by=</span><span class="dv">2</span>), <span class="dt">dog=</span>LETTERS[<span class="dv">1</span><span class="op">:</span><span class="dv">5</span>], <span class="dt">hasStyle=</span><span class="kw">logical</span>(<span class="dv">5</span>) )
<span class="kw">summary</span>(theList)</code></pre></div>
<pre><code>##          Length Class  Mode     
## x        20     -none- numeric  
## dog       5     -none- character
## hasStyle  5     -none- logical</code></pre>
<p>which is defined with a numeric, a character, and a logical component. Each of these entries can be different in length as well as type. Once defined, the entries may be observed as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">theList</code></pre></div>
<pre><code>## $x
##  [1]  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40
## 
## $dog
## [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; &quot;E&quot;
## 
## $hasStyle
## [1] FALSE FALSE FALSE FALSE FALSE</code></pre>
<p>Once created, you can add variables to the list using the $-operator followed by the name of the key for the new entry.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">theList<span class="op">$</span>my_favoriate_number &lt;-<span class="st"> </span><span class="fl">2.9</span> <span class="op">+</span><span class="st"> </span>3i</code></pre></div>
<p>or use double brackets and the name of the variable as a character string.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">theList[[<span class="st">&quot;lotto numbers&quot;</span>]] &lt;-<span class="st"> </span><span class="kw">rpois</span>(<span class="dv">7</span>,<span class="dt">lambda=</span><span class="dv">42</span>)</code></pre></div>
<p>The keys currently in the list are given by the <code>names()</code> function</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">names</span>(theList)</code></pre></div>
<pre><code>## [1] &quot;x&quot;                   &quot;dog&quot;                 &quot;hasStyle&quot;           
## [4] &quot;my_favoriate_number&quot; &quot;lotto numbers&quot;</code></pre>
<p>Getting and setting values within a list are done the same way using either the <code>$</code>-operator</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">theList<span class="op">$</span>x</code></pre></div>
<pre><code>##  [1]  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">theList<span class="op">$</span>x[<span class="dv">2</span>] &lt;-<span class="st"> </span><span class="dv">42</span>
theList<span class="op">$</span>x</code></pre></div>
<pre><code>##  [1]  2 42  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40</code></pre>
<p>or the double brackets</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">theList[[<span class="st">&quot;x&quot;</span>]]</code></pre></div>
<pre><code>##  [1]  2 42  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40</code></pre>
<p>or using a numeric index, but that numeric index is looks to the results of <code>names()</code> to figure out which key to use.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">theList[[<span class="dv">2</span>]]</code></pre></div>
<pre><code>## [1] &quot;A&quot; &quot;B&quot; &quot;C&quot; &quot;D&quot; &quot;E&quot;</code></pre>
<p>The use of the double brackets in essence provides a direct link to the variable in the list whose name is second in the <code>names()</code> function (<em>dog</em> in this case). If you want to access elements within that variable, then you add a second set of brackets on after the double ones.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">theList[[<span class="dv">1</span>]][<span class="dv">3</span>]</code></pre></div>
<pre><code>## [1] 6</code></pre>
<p>This deviates from the matrix approach as well as from how we access entries in a <code>data.frame</code> (described next). It is not a single square bracket with two indices, that gives you an error:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">theList[<span class="dv">1</span>,<span class="dv">3</span>] </code></pre></div>
<pre><code>## Error in theList[1, 3] : incorrect number of dimensions
## Calls: &lt;Anonymous&gt; ... handle -&gt; withCallingHandlers -&gt; withVisible -&gt; eval -&gt; eval
## Execution halted</code></pre>
<p>List are rather robust objects that allow you to store a wide variety of data types (including nested lists). Once you get the indexing scheme down, it they will provide nice solutions for many of your computational needs.</p>
</div>
<div id="data-frames" class="section level3">
<h3><span class="header-section-number">5.7.13</span> Data Frames</h3>
<p>The <code>data.frame</code> is the default data container in R. It is analogous to both a spreadsheet, at least in the way that I have used spreadsheets in the past, as well as a database. If you consider a single spreadsheet containing measurements and observations from your research, you may have many columns of data, each of which may be a different kind of data. There may be <code>factors</code> representing designations such as species, regions, populations, sex, flower color, etc. Other columns may contain numeric data types for items such as latitude, longitude, dbh, and nectar sugar content. You may also have specialized columns such as dates collected, genetic loci, and any other information you may be collecting.</p>
<p>On a spreadsheet, each column has a unified data type, either quantified with a value or as a missing value, <code>NA</code>, in each row. Rows typically represent the sampling unit, perhaps individual or site, along which all of these various items have been measured or determined. A <code>data.frame</code> is similar to this, at least conceptually. You define a <code>data.frame</code> by designating the columns of data to be used. You do not need to define all of them, more can be added later. The values passed can be sequences, collections of values, or computed parameters. For example:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df &lt;-<span class="st"> </span><span class="kw">data.frame</span>( <span class="dt">ID=</span><span class="dv">1</span><span class="op">:</span><span class="dv">5</span>, <span class="dt">Names=</span><span class="kw">c</span>(<span class="st">&quot;Bob&quot;</span>,<span class="st">&quot;Alice&quot;</span>,<span class="st">&quot;Vicki&quot;</span>,<span class="st">&quot;John&quot;</span>,<span class="st">&quot;Sarah&quot;</span>), <span class="dt">Score=</span><span class="dv">100</span> <span class="op">-</span><span class="st"> </span><span class="kw">rpois</span>(<span class="dv">5</span>,<span class="dt">lambda=</span><span class="dv">10</span>))
df</code></pre></div>
<pre><code>##   ID Names Score
## 1  1   Bob    88
## 2  2 Alice    84
## 3  3 Vicki    87
## 4  4  John    88
## 5  5 Sarah    93</code></pre>
<p>You can see that each column is a unified type of data and each row is equivalent to a record. Additional data columns may be added to an existing data.frame as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df<span class="op">$</span>Passed_Class &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="ot">TRUE</span>,<span class="ot">TRUE</span>,<span class="ot">TRUE</span>,<span class="ot">FALSE</span>,<span class="ot">TRUE</span>)</code></pre></div>
<p>Since we may have many (thousands?) of rows of observations, a <code>summary()</code> of the data.frame can provide a more compact description.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">summary</span>(df)</code></pre></div>
<pre><code>##        ID       Names               Score    Passed_Class   
##  Min.   :1   Length:5           Min.   :84   Mode :logical  
##  1st Qu.:2   Class :character   1st Qu.:87   FALSE:1        
##  Median :3   Mode  :character   Median :88   TRUE :4        
##  Mean   :3                      Mean   :88                  
##  3rd Qu.:4                      3rd Qu.:88                  
##  Max.   :5                      Max.   :93</code></pre>
<p>We can add columns of data to the data.frame after the fact using the <code>$</code>-operator to indicate the column name. Depending upon the data type, the summary will provide an overview of what is there.</p>
<div id="indexing-data-frames" class="section level4">
<h4><span class="header-section-number">5.7.13.1</span> Indexing Data Frames</h4>
<p>You can access individual items within a <code>data.frame</code> by numeric index such as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df[<span class="dv">1</span>,<span class="dv">3</span>]</code></pre></div>
<pre><code>## [1] 88</code></pre>
<p>You can slide indices along rows (which return a new <code>data.frame</code> for you)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df[<span class="dv">1</span>,]</code></pre></div>
<pre><code>##   ID Names Score Passed_Class
## 1  1   Bob    88         TRUE</code></pre>
<p>or along columns (which give you a vector of data)</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df[,<span class="dv">3</span>]</code></pre></div>
<pre><code>## [1] 88 84 87 88 93</code></pre>
<p>or use the <code>$</code>-operator as you did for the list data type to get direct access to a either all the data or a specific subset therein.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df<span class="op">$</span>Names[<span class="dv">3</span>]</code></pre></div>
<pre><code>## [1] &quot;Vicki&quot;</code></pre>
<p>Indices are ordered just like for matrices, rows first then columns. You can also pass a set of indices such as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df[<span class="dv">1</span><span class="op">:</span><span class="dv">3</span>,]</code></pre></div>
<pre><code>##   ID Names Score Passed_Class
## 1  1   Bob    88         TRUE
## 2  2 Alice    84         TRUE
## 3  3 Vicki    87         TRUE</code></pre>
<p>It is also possible to use logical operators as indices. Here I select only those names in the data.frame whose score was &gt;90 and they passed popgen.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">df<span class="op">$</span>Names[df<span class="op">$</span>Score <span class="op">&gt;</span><span class="st"> </span><span class="dv">90</span> <span class="op">&amp;</span><span class="st"> </span>df<span class="op">$</span>Passed_Class<span class="op">==</span><span class="ot">TRUE</span>]</code></pre></div>
<pre><code>## [1] &quot;Sarah&quot;</code></pre>
<p>This is why <code>data.frame</code> objects are very database like. They can contain lots of data and you can extract from them subsets that you need to work on. This is a VERY important feature, one that is vital for reproducible research. Keep you data in one and only one place.</p>
</div>
</div>
</div>
<div id="programming" class="section level2">
<h2><span class="header-section-number">5.8</span> Programming</h2>
<p>One of the strengths of R as an analysis platform is that it is a language rather than a program. With programs, such as SPSS &amp; JMP, you are limited by the functionality that the designers thought would be necessary to meet the broadest audience. In R, you can rely upon simple functions or you can create entire analysis and simulation programs de novo. To do this, we need to dig into flow control and decision making processes, both of which you need for doing more in-depth programming.</p>
<div id="function-writing" class="section level3">
<h3><span class="header-section-number">5.8.1</span> Function Writing</h3>
<p>Here we look at how to create an R function. Writing small functions like this is a huge benefit to you as an analyst and this is a great place to start. A function in R is defined as:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">function_name &lt;-<span class="st"> </span><span class="cf">function</span>( arguments ) { Stuff you want the <span class="cf">function</span> to do }</code></pre></div>
<p>You define a function name for whatever you like and assign it the stuff to the right. In R, the function named <code>function()</code> is a special one, it tells R that you are about to create a little routine and you want that set of code to be available to you for later use under the name of whatever you named it. This allows a tremendous amount of flexibility as you develop your own set of routines and analyses for your work. The part that actually does stuff is after the function call. It may be that the function that you create does need some data (those are the arguments) or you may not need any input in to the function (in which you pass no arguments). It all depends upon what you are creating.</p>
<p>The key to understanding functions is that they are encapsulations of code—a shortcut for a sequence of instructions if you will not have to type over and over again. The less typing you do, the lower the probability that you will have errors (and all code has errors).</p>
<p>Here is an example of some code that I’m going to develop into a function. This function will allow me to determine if one genotype could possibly be the offspring of the other genotype.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">library</span>(gstudio)
loc1 &lt;-<span class="st"> </span><span class="kw">locus</span>( <span class="kw">c</span>(<span class="dv">128</span>,<span class="dv">130</span>) )
loc2 &lt;-<span class="st"> </span><span class="kw">locus</span>( <span class="kw">c</span>(<span class="dv">128</span>,<span class="dv">128</span>) )
<span class="kw">cat</span>( loc1, loc2 )</code></pre></div>
<pre><code>## 128:130 128:128</code></pre>
<p>We start out with two loci, a <code>128:130</code> heterozygote and a <code>128:128</code> homozygote. These may represent repeat motifs at a microsatellite locus or some other co-dominant genotype. First, I’ll break the locus into a vector of genotypes.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">off.alleles &lt;-<span class="st"> </span><span class="kw">alleles</span>( loc1 )
off.alleles</code></pre></div>
<pre><code>## [1] &quot;128&quot; &quot;130&quot;</code></pre>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">mom.alleles &lt;-<span class="st"> </span><span class="kw">alleles</span>( loc2 )
mom.alleles</code></pre></div>
<pre><code>## [1] &quot;128&quot; &quot;128&quot;</code></pre>
<p>To be a valid potential offspring there should be at least one of the alleles in the parent that matches the allele in the offspring. The <code>intersect()</code> function returns the set of values common to both vectors.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">shared &lt;-<span class="st"> </span><span class="kw">intersect</span>( off.alleles, mom.alleles )
shared</code></pre></div>
<pre><code>## [1] &quot;128&quot;</code></pre>
<p>If it has at least one of the alleles present (it could have both if parent and offspring are both the same heterozygote) then you cannot exclude this individual as a potential offspring. If there are no alleles in common, then the value returned is an empty vector.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">loc3 &lt;-<span class="st"> </span><span class="kw">locus</span>( <span class="kw">c</span>(<span class="dv">132</span>,<span class="dv">132</span>))
dad.alleles &lt;-<span class="st"> </span><span class="kw">alleles</span>( loc3 )
<span class="kw">intersect</span>( mom.alleles, dad.alleles )</code></pre></div>
<pre><code>## character(0)</code></pre>
<p>This logic can be shoved into a function. You have to wrap it into a set of curly brackets. I use the length of the result from the intersect() to return from the function. Potential values for</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">potential_offspring &lt;-<span class="st"> </span><span class="cf">function</span>( parent, offspring ) {
  off &lt;-<span class="st"> </span><span class="kw">alleles</span>( offspring )
  par &lt;-<span class="st"> </span><span class="kw">alleles</span>( loc2 )
  shared &lt;-<span class="st"> </span><span class="kw">intersect</span>( off, par )
  <span class="kw">return</span>( <span class="kw">length</span>( shared ) <span class="op">&gt;</span><span class="st"> </span><span class="dv">0</span> )
}</code></pre></div>
<p>Now, you can call this function anytime you need, just passing it two genotypes. If they can be offspring it returns TRUE, as in the comparison between 128:130 and 128:128 genotypes.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">potential_offspring</span>(loc1, loc2)</code></pre></div>
<pre><code>## [1] TRUE</code></pre>
<p>And it returns FALSE for the comparison between 128:128 and 132:132.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">potential_offspring</span>(loc2, loc3)</code></pre></div>
<pre><code>## [1] FALSE</code></pre>
</div>
<div id="variable-scope" class="section level3">
<h3><span class="header-section-number">5.8.2</span> Variable Scope</h3>
<p>There is a lot more information on writing functions and we will get into that as we progress through the text. However, it is important that I bring this up now. The value assigned to a variable is defined by its scope. Consider the following code</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="dv">10</span></code></pre></div>
<p>and the function defined as</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">do_it &lt;-<span class="st"> </span><span class="cf">function</span>( x ) {
  x &lt;-<span class="st"> </span>x <span class="op">+</span><span class="st"> </span><span class="dv">10</span>
  <span class="kw">return</span>( x )
}</code></pre></div>
<p>When I call the function, the variable x that is the argument of the function is not the same variable that is in the environment that I assigned a value of 10. The x in the function argument is what we call “local to that function” in that within the curly brackets that follow (and any number of curly brackets nested within those, the value of x is given whatever was passed to the function.</p>
</div>
<div id="decision-making" class="section level3">
<h3><span class="header-section-number">5.8.3</span> Decision Making</h3>
<p>We interact with our data in many ways and introspection of the values we have in the variables we are working with are of prime importance. Decision making in your code is where you evaluate your data and make a choice of outcomes based upon some criteria. Here is some example data that we can use as we explore the basics of <code>if()</code>, <code>if(){} else{}</code>, and <code>if(){} elif(){} else{}</code> coding patterns.</p>
<div id="the-if-pattern" class="section level4">
<h4><span class="header-section-number">5.8.3.1</span> The <code>if</code> Pattern</h4>
<p>The most basic version of decision making is asking a single question and if the answer is TRUE then do something. The <code>if(){}</code> function does this and has the form</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">if</span>( CRITERIA ) {
    DO_SOMETHING
}</code></pre></div>
<p>You pass a logical statement (or something that can be coerced into a logical type) to the function as the CRITERIA and if it evaluates to <code>TRUE</code>, then the contents of the <code>DO_SOMETHING</code> are executed. If the value of <code>CRITERIA</code> is not <code>TRUE</code> the <code>DO_SOMETHING</code> is skipped entirely—it is not even seen by the interpreter.</p>
<p>Here we can test this out using the loci defined above along with the is_heterozygote() function. This function takes one or more locus objects and returns TRUE/FALSE if they are or are not a heterozygote.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="kw">is_heterozygote</span>( <span class="kw">c</span>(loc1, loc2) )</code></pre></div>
<pre><code>## [1]  TRUE FALSE</code></pre>
<p>If we shove that function into the <code>if()</code> parameters we can use its evaluation of the heterozygous state of the locus to do something interesting, say tell us it is a heterozygote—it is admittedly a contrived example, but hey you try to make easy examples, it is not easy.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">if</span>( <span class="kw">is_heterozygote</span>(loc1) ){
  <span class="kw">print</span>(<span class="st">&quot;It&#39;s a het!&quot;</span>)
}</code></pre></div>
<pre><code>## [1] &quot;It&#39;s a het!&quot;</code></pre>
<p>If the <code>is_heterozygote()</code> function returns a value of FALSE, then the contents of the <code>if()</code> function (the stuff within the curly brackets is skipped entirely.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">if</span>( <span class="kw">is_heterozygote</span>(loc2) ){
  <span class="kw">print</span>(<span class="st">&quot;It&#39;s a het!&quot;</span>)
}</code></pre></div>
<p>Notice, there was no indication of any of that code inside the curly brackets. The if-else Pattern If there are more than on thing you want to potentially do when making a decision, you can add an else clause after the if pattern. Here if is_heterozygote() returns FALSE, the contents of the else{} clause will be executed. Here is the heterozygote example</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">if</span>( <span class="kw">is_heterozygote</span>(loc1) ) {
  <span class="kw">cat</span>(loc1, <span class="st">&quot;is a heterozygote&quot;</span>)
} <span class="cf">else</span> {
  <span class="kw">cat</span>(loc1, <span class="st">&quot;is a homozygote&quot;</span>)
}</code></pre></div>
<pre><code>## 128:130 is a heterozygote</code></pre>
<p>and the homozygote one</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">if</span>( <span class="kw">is_heterozygote</span>(loc2) ) {
  <span class="kw">cat</span>(loc2, <span class="st">&quot;is a heterozygote&quot;</span>)
} <span class="cf">else</span> {
  <span class="kw">cat</span>(loc2, <span class="st">&quot;is a homozygote&quot;</span>)
}</code></pre></div>
<pre><code>## 128:128 is a homozygote</code></pre>
<p>There is a slightly shorter version of this that is available for the lazy programmer and lets be honest, all programmers are lazy and the more you can accomplish with fewer strokes on the keyboard the better (this is how we got emacs and vim). I generally don’t teach the shortcuts up front, but this one is short and readily apparent so it may be more helpful than confusing. The <code>ifelse()</code> function has three parts, the condition, the result if <code>TRUE</code>, and the result if <code>FALSE</code>.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">ans &lt;-<span class="st"> </span><span class="kw">ifelse</span>( <span class="kw">is_heterozygote</span>( <span class="kw">c</span>(loc1, loc2)) , <span class="st">&quot;heterozygote&quot;</span>, <span class="st">&quot;Not&quot;</span>)
ans</code></pre></div>
<pre><code>## [1] &quot;heterozygote&quot; &quot;Not&quot;</code></pre>
<p>So iterating through the x vector, the condition <code>x&gt;0</code> is evaluated and if TRUE the sqrt() of the value is returned, else the NA is given. It is compact and easy to use so you may run into it often.</p>
</div>
<div id="the-if-else-pattern" class="section level4">
<h4><span class="header-section-number">5.8.3.2</span> The <code>if-else</code> Pattern</h4>
<p>It is possible to test many conditions in a single sequence by stringing together else-if conditions. The point that is important here is that the first condition that evaluates to TRUE will be executed and all remaining ones will be skipped, even if they also are logically TRUE. This means that it is important to figure out the proper order of asking your conditions. Here is an example function that determines if none, one, or both of the genotypes passed to it are heterozygotes. By default, I step through every one of the potential options of available on this comparison.<br />
1. The first is a heterozygote and the second one isn’t 2. The first one isn’t and the second one is 3. Both are heterozygotes 4. The last state (both are not)</p>
<p>Here is the function.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">which_is_het &lt;-<span class="st"> </span><span class="cf">function</span>( A, B) {
  <span class="cf">if</span>( <span class="kw">is_heterozygote</span>(A) <span class="op">&amp;</span><span class="st"> </span><span class="op">!</span><span class="kw">is_heterozygote</span>(B) ) {
    <span class="kw">print</span>(<span class="st">&quot;First is heterozygote&quot;</span>)
  } <span class="cf">else</span> <span class="cf">if</span>( <span class="op">!</span><span class="kw">is_heterozygote</span>(A) <span class="op">&amp;</span><span class="st"> </span><span class="kw">is_heterozygote</span>(B) ){
    <span class="kw">print</span>(<span class="st">&quot;Second is heterozygote&quot;</span>)
  } <span class="cf">else</span> <span class="cf">if</span>( <span class="kw">is_heterozygote</span>(A) <span class="op">&amp;</span><span class="st"> </span><span class="kw">is_heterozygote</span>(B) ){
    <span class="kw">print</span>(<span class="st">&quot;Both are heterozygotes&quot;</span>)
  } <span class="cf">else</span> {
    <span class="kw">print</span>( <span class="st">&quot;Neither are heterozygotes&quot;</span>)
  }
}</code></pre></div>
<p>It is possible that the order of these CRITERIA could be changed, the important thing to remember is that the sequence of if - else if - else if etc. will terminate the very first time one of the CRITERIA is evaluated to be <code>TRUE</code>.</p>
</div>
</div>
<div id="flow-control" class="section level3">
<h3><span class="header-section-number">5.8.4</span> Flow Control</h3>
<p>Flow control is the process of iterating across objects and perhaps doing operations on those objects. The R language has several mechanisms that you can use to control the flow of a script or bit of code.</p>
<div id="the-for-loop" class="section level4">
<h4><span class="header-section-number">5.8.4.1</span> The for() Loop</h4>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">x &lt;-<span class="st"> </span><span class="kw">c</span>(<span class="dv">3</span>,<span class="dv">8</span>,<span class="dv">5</span>,<span class="dv">4</span>,<span class="dv">6</span>)
x</code></pre></div>
<pre><code>## [1] 3 8 5 4 6</code></pre>
<p>You can iterate through this vector using a for() loop. This is a simple function that has the form:</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span>( SOME_SEQUENCE ){
  DO_SOMETHING
}</code></pre></div>
<p>Where the <code>SOME_SEQUENCE</code> component is a sequence of values either specified OR calculated and the <code>DO_SOMETHING</code> is the thing you want to do with each of the values in the sequence. Usually, there is a variable defined in the <code>SOME_SEQUENCE</code> component and the value of that variable is used. Here are a few examples. The first goes through the existing vector directly and assigns (in sequential order) the entries of ‘x’ to the variable val. We can then do whatever we want with the value in val (though if we change it, nothing happens to the original x vector).</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span>( val <span class="cf">in</span> x ){
  <span class="kw">print</span>(val)
}</code></pre></div>
<pre><code>## [1] 3
## [1] 8
## [1] 5
## [1] 4
## [1] 6</code></pre>
<p>We can also specify a sequence directly and then use it as an index. Here I use an index variable named i to take on the integer seqeunce equal in length to the length of the original <code>x</code> variable. Then I can iterate through the original vector and use that index variable to grab the value I want.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(x)){
  <span class="kw">print</span>( x[i] )
}</code></pre></div>
<pre><code>## [1] 3
## [1] 8
## [1] 5
## [1] 4
## [1] 6</code></pre>
<p>Both give us the same output, namely a way to go through the variable <code>x</code>. However, there may be a need to use the latter approach in your calculations. For example, perhaps I want to do some other operation on the values. In this very contrived example that follows, I want to perform operations on the values in <code>x</code> depending on if they are even or odd. For the odd ones, I add the corresponding value in <code>y</code> and if not I subtract it. Sure, this is totally contrived and I cannot think of a reason why I would be doing this, but if I need to know what index (row, column or whatever) an entry is during the iteration process, then I need to use this approach over the <code>for( val in x)</code> approach.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r">y &lt;-<span class="st"> </span><span class="dv">1</span><span class="op">:</span><span class="dv">5</span>
<span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="kw">length</span>(x)){
  <span class="cf">if</span>( x[i] <span class="op">%%</span><span class="st"> </span><span class="dv">2</span>)
    <span class="kw">print</span>( x[i] <span class="op">+</span><span class="st"> </span>y[i])
  <span class="cf">else</span>
    <span class="kw">print</span>( x[i] <span class="op">-</span><span class="st"> </span>y[i] )
}</code></pre></div>
<pre><code>## [1] 4
## [1] 6
## [1] 8
## [1] 0
## [1] 1</code></pre>
</div>
<div id="short-circuiting-the-loop" class="section level4">
<h4><span class="header-section-number">5.8.4.2</span> Short Circuiting the Loop</h4>
<p>It is possible to short circuit the looping process using the keywords next and break, though in my programming style, I consider their use in my source files as evidence of inelegant code. That said, you may need them on occasion.</p>
<p>The next keyword basically stops all commands after that during the current iteration of the loop. It does not terminate the loop itself, it just stops the commands that follow it this time through. Here is an example that uses the modulus operator, <code>%%</code> (e.g., the remainder after division), to print out only those numbers that are divisible by three.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">20</span> ){
  <span class="cf">if</span>( i <span class="op">%%</span><span class="st"> </span><span class="dv">3</span> )
    <span class="cf">next</span>
  <span class="kw">cat</span>(<span class="st">&quot;The value of i =&quot;</span>,i,<span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)
}</code></pre></div>
<pre><code>## The value of i = 3 
## The value of i = 6 
## The value of i = 9 
## The value of i = 12 
## The value of i = 15 
## The value of i = 18</code></pre>
<p>The use of break to exit the loop entirely is perhaps more commonly encountered. When this keyword is encountered, the loop terminates immediately, as if it reached the send of the sequence.</p>
<div class="sourceCode"><pre class="sourceCode r"><code class="sourceCode r"><span class="cf">for</span>( i <span class="cf">in</span> <span class="dv">1</span><span class="op">:</span><span class="dv">10</span>){
  <span class="cf">if</span>( i <span class="op">&gt;</span><span class="st"> </span><span class="dv">2</span> )
    <span class="cf">break</span>
  <span class="kw">cat</span>(<span class="st">&quot;The value of i=&quot;</span>,i,<span class="st">&quot;</span><span class="ch">\n</span><span class="st">&quot;</span>)
}</code></pre></div>
<pre><code>## The value of i= 1 
## The value of i= 2</code></pre>

</div>
</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="1">
<li id="fn1"><p>The word <em>data</em> is plural, datum is singular<a href="the-r-environment.html#fnref1">↩</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="adaptive-landscape-genetics.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="references-cited.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/lunr.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": false,
"twitter": false,
"google": false,
"weibo": false,
"instapper": false,
"vk": false,
"all": ["facebook", "google", "twitter", "weibo", "instapaper"],
"instapaper": false
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": null,
"text": null
},
"download": null,
"toc": {
"collapse": "section",
"scroll_highlight": true
},
"search": true
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://cdn.bootcss.com/mathjax/2.7.1/MathJax.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:" && /^https?:/.test(script.src))
      script.src  = script.src.replace(/^https?:/, '');
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
